/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 408e98305e426ff23231553f662ad0c7)
interface __BaseEnv_Env {
	IMAGE_BUCKET: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	ASSETS: Fetcher;
	IMAGES_PUBLIC_URL: "https://images.langmap.io";
	R2_IMAGES_BUCKET: "langmap-images";
	CLOUDFLARE_ACCOUNT_ID: "0dd310069a11740f48708e490bb1aede";
	SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "IMAGES_PUBLIC_URL" | "R2_IMAGES_BUCKET" | "CLOUDFLARE_ACCOUNT_ID" | "SECRET_KEY">> {}
}
