/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e0caaf2be5c72e1ddd4364a65320b87b)
interface __BaseEnv_Env {
	IMAGE_BUCKET: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SECRET_KEY">> {}
}
