/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 15cb6dee4de2635153ba7e9bd478fe9d)
interface __BaseEnv_Env {
	IMAGE_BUCKET: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	IMAGES_PUBLIC_URL: "https://images.langmap.io";
	R2_IMAGES_BUCKET: "langmap-images";
	SECRET_KEY: string;
	CLOUDFLARE_API_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "IMAGES_PUBLIC_URL" | "R2_IMAGES_BUCKET" | "SECRET_KEY" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_ACCOUNT_ID">> {}
}
