#!/usr/bin/env python3
"""Generate the pinned ISO language-reference seed SQL + manifest.

Offline and deterministic: reads committed raw/ + overlays/, emits fixed-sorted
artifacts/language-reference.sql and artifacts/manifest.json. No network access.
"""
from __future__ import annotations

import csv
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RAW = ROOT / "raw"
OVERLAYS = ROOT / "overlays"
ARTIFACTS = ROOT / "artifacts"

MIN_LANGUAGES = 7000
MIN_SCRIPTS = 100
MIN_REGIONS = 200


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def read_languages() -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    with (RAW / "iso639-3.tab").open(encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh, delimiter="\t"):
            if row.get("Scope") != "I":
                continue
            code = (row.get("Id") or "").strip().lower()
            name = (row.get("Ref_Name") or "").strip()
            if code and name:
                rows.append((code, name))
    rows.sort()
    return rows


def read_script_directions() -> dict[str, str]:
    data = json.loads((OVERLAYS / "script-directions.json").read_text(encoding="utf-8"))
    cleaned: dict[str, str] = {}
    for k, v in data.items():
        if v not in ("ltr", "rtl"):
            raise ValueError(f"invalid direction {v!r} for {k!r}")
        cleaned[k.strip()] = v
    return cleaned


def read_scripts(directions: dict[str, str]) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    with (RAW / "iso15924.txt").open(encoding="utf-8") as fh:
        for line in fh:
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            parts = [p.strip() for p in line.split(";")]
            if len(parts) < 2 or not parts[0] or not parts[1]:
                continue
            code, name = parts[0], parts[1]
            direction = directions.get(code)
            if direction is None:
                raise ValueError(f"script {code!r} missing curated direction overlay")
            rows.append((code, name, direction))
    rows.sort()
    return rows


def read_region_coords() -> dict[str, tuple[float | None, float | None]]:
    coords: dict[str, tuple[float | None, float | None]] = {}
    path = OVERLAYS / "region-coordinates.tsv"
    if not path.exists():
        return coords
    with path.open(encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh, delimiter="\t"):
            code = (row.get("code") or "").strip()
            if not code:
                continue
            lat = float(row["latitude"]) if row.get("latitude") else None
            lon = float(row["longitude"]) if row.get("longitude") else None
            if (lat is None) != (lon is None):
                raise ValueError(f"region {code!r} has unpaired coordinates")
            coords[code] = (lat, lon)
    return coords


def read_regions(coords: dict[str, tuple[float | None, float | None]]) -> list[tuple[str, str, float | None, float | None]]:
    rows: list[tuple[str, str, float | None, float | None]] = []
    with (RAW / "iso3166-1.tsv").open(encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh, delimiter="\t"):
            code = (row.get("code") or "").strip()
            name = (row.get("name_en") or "").strip()
            if not code or not name:
                continue
            lat, lon = coords.get(code, (None, None))
            rows.append((code, name, lat, lon))
    rows.sort()
    return rows


INSERT_BATCH = 500


def _insert_blocks(table: str, columns: list[str], value_rows: list[str]) -> list[str]:
    # D1/miniflare rejects oversized single statements (SQLITE_TOOBIG), so chunk
    # each table into multiple INSERT statements of at most INSERT_BATCH rows.
    cols = ", ".join(columns)
    out: list[str] = []
    for i in range(0, len(value_rows), INSERT_BATCH):
        chunk = value_rows[i:i + INSERT_BATCH]
        out.append(f"INSERT OR IGNORE INTO {table} ({cols}) VALUES")
        out.append(",\n".join(chunk) + ";")
    return out


def emit_sql(
    languages: list[tuple[str, str]],
    scripts: list[tuple[str, str, str]],
    regions: list[tuple[str, str, float | None, float | None]],
) -> str:
    lines: list[str] = ["-- AUTO-GENERATED by scripts/language-reference/generate.py. Do not edit."]

    lang_vals = [f"  ({sql_str(c)}, {sql_str(n)})" for c, n in languages]
    lines += _insert_blocks("languages", ["code", "name_en"], lang_vals)

    script_vals = [f"  ({sql_str(c)}, {sql_str(n)}, {sql_str(d)})" for c, n, d in scripts]
    lines += _insert_blocks("scripts", ["code", "name_en", "direction"], script_vals)

    region_vals: list[str] = []
    for c, n, lat, lon in regions:
        lat_s = "NULL" if lat is None else repr(lat)
        lon_s = "NULL" if lon is None else repr(lon)
        region_vals.append(f"  ({sql_str(c)}, {sql_str(n)}, {lat_s}, {lon_s})")
    lines += _insert_blocks("regions", ["code", "name_en", "latitude", "longitude"], region_vals)

    return "\n".join(lines) + "\n"


def build_manifest(languages, scripts, regions, directions, region_coords, sql_text) -> dict:
    def src(name: str, path: Path, **extra) -> dict:
        payload = {
            "name": name,
            "path": str(path.relative_to(ROOT)),
            "sha256": sha256_file(path),
            "size": path.stat().st_size,
        }
        payload.update(extra)
        return payload

    return {
        "manifest_version": 1,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "sources": {
            "iso639-3": src("ISO 639-3 (individual scope)", RAW / "iso639-3.tab", license="FSFAP", source="Debian iso-codes (mirrors SIL)"),
            "iso15924": src("ISO 15924", RAW / "iso15924.txt", license="Unicode-DFS-2016", source="unicode.org"),
            "iso3166-1": src("ISO 3166-1 alpha-2", RAW / "iso3166-1.tsv", license="FSFAP", source="Debian iso-codes"),
        },
        "overlays": {
            "script_directions": {"path": "overlays/script-directions.json", "covered_scripts": len(directions)},
            "region_coordinates": {"path": "overlays/region-coordinates.tsv", "covered_regions": len(region_coords)},
        },
        "counts": {
            "languages": len(languages),
            "scripts": len(scripts),
            "regions": len(regions),
        },
        "artifacts": {
            "language_reference_sql": {
                "path": "language-reference.sql",
                "sha256": hashlib.sha256(sql_text.encode("utf-8")).hexdigest(),
            }
        },
    }


def main() -> int:
    directions = read_script_directions()
    region_coords = read_region_coords()
    languages = read_languages()
    scripts = read_scripts(directions)
    regions = read_regions(region_coords)

    if len(languages) < MIN_LANGUAGES:
        raise SystemExit(f"languages count {len(languages)} < {MIN_LANGUAGES}")
    if len(scripts) < MIN_SCRIPTS:
        raise SystemExit(f"scripts count {len(scripts)} < {MIN_SCRIPTS}")
    if len(regions) < MIN_REGIONS:
        raise SystemExit(f"regions count {len(regions)} < {MIN_REGIONS}")

    sql_text = emit_sql(languages, scripts, regions)
    manifest = build_manifest(languages, scripts, regions, directions, region_coords, sql_text)

    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    (ARTIFACTS / "language-reference.sql").write_text(sql_text, encoding="utf-8")
    (ARTIFACTS / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {ARTIFACTS / 'language-reference.sql'} ({len(languages)} languages, {len(scripts)} scripts, {len(regions)} regions)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
