-- AUTO-GENERATED by scripts/i18n/generate-bundle.py. Do not edit.
-- Project: langmap-web; direct UI translation semantic edges.
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mapLens.noData', 'No hay datos de distribución geográfica para esta expresión'),
  ('spa-Latn-ES', 'spa', 'mapLens.regions', '{count} regiones'),
  ('spa-Latn-ES', 'spa', 'mapLens.title', 'Distribución de la expresión'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.addAndMap', 'Añadir y crear relación'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.addExpression', 'Añadir expresión')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mappingDetail.addFailed', 'No se pudo añadir la expresión'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.adding', 'Añadiendo…'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.allLanguages', 'Todos los idiomas'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.authority', 'Autoridad'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.breadcrumb', 'Ruta de navegación')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mappingDetail.closeQuickAdd', 'Cerrar adición rápida'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.contribute', 'Contribuir relación'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.direct', 'relaciones directas'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.enterRequired', 'Introduce expresión y código de idioma'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.expression', 'Expresión')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mappingDetail.expressionPlaceholder', 'Introduce una expresión…'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.graph', 'Grafo'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.graphTruncated', 'El grafo se ha truncado; se omitieron {count} expresiones relacionadas.'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.home', 'Inicio'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.hops', 'saltos')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mappingDetail.indirect', 'indirecta'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.languageCode', 'Código de idioma'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.languageCodePlaceholder', 'ej. en / cmn-Hant'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.list', 'Lista'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.loadFailed', 'No se pudo cargar')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mappingDetail.mappingSet', 'Conjunto de relaciones'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.noMappings', 'Aún no hay relaciones'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.optional', 'Opcional'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.quickAdd', 'Añadir expresión rápidamente'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.quickAddLead', 'Añade una expresión y relaciónala directamente con la expresión actual.')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mappingDetail.region', 'Región'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.splitExpression', 'Dividir expresión'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.splitFailed', 'No se pudo dividir la expresión'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.splitLoadFailed', 'No se pudieron cargar las relaciones para dividir'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.targetLanguage', 'Idioma de destino')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mappingDetail.user', 'Usuario'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.viewMap', 'Ver esta expresión en el mapa'),
  ('spa-Latn-ES', 'spa', 'morphology.addFormLink', 'Añadir enlace de forma'),
  ('spa-Latn-ES', 'spa', 'morphology.class.adjective', 'Adjetivo'),
  ('spa-Latn-ES', 'spa', 'morphology.class.noun', 'Sustantivo')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'morphology.class.verb', 'Verbo'),
  ('spa-Latn-ES', 'spa', 'morphology.dictionaryForm', 'Forma de diccionario'),
  ('spa-Latn-ES', 'spa', 'morphology.empty', 'Aún no hay enlaces de forma'),
  ('spa-Latn-ES', 'spa', 'morphology.formOfAria', 'Forma de {lemma}: {features}'),
  ('spa-Latn-ES', 'spa', 'morphology.hideForm', 'Ocultar formulario')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'morphology.loadFailed', 'No se pudieron cargar las formas'),
  ('spa-Latn-ES', 'spa', 'morphology.markAsForm', 'Marcar como forma de…'),
  ('spa-Latn-ES', 'spa', 'morphology.noLanguageFeatures', 'No hay rasgos habituales para esta clase. Puedes guardar el enlace o mostrar todos los rasgos.'),
  ('spa-Latn-ES', 'spa', 'morphology.pickFeatures', 'Rasgos'),
  ('spa-Latn-ES', 'spa', 'morphology.pickFeaturesHint', 'Opcional. Solo se muestran los rasgos habituales de este idioma y esta clase.')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'morphology.saved', 'Enlace de forma guardado'),
  ('spa-Latn-ES', 'spa', 'morphology.saving', 'Guardando…'),
  ('spa-Latn-ES', 'spa', 'morphology.searchLemma', 'Buscar una forma de diccionario en el mismo idioma'),
  ('spa-Latn-ES', 'spa', 'morphology.searchLemmaLabel', 'Forma de diccionario'),
  ('spa-Latn-ES', 'spa', 'morphology.showAllFeatures', 'Mostrar todos los rasgos')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'morphology.submit', 'Guardar enlace de forma'),
  ('spa-Latn-ES', 'spa', 'morphology.submitFailed', 'No se pudo guardar el enlace de forma'),
  ('spa-Latn-ES', 'spa', 'morphology.title', 'Formas de la palabra'),
  ('spa-Latn-ES', 'spa', 'morphology.wordClass', 'Clase de palabra'),
  ('spa-Latn-ES', 'spa', 'morphology.wordClassHint', 'Elige primero sustantivo, verbo o adjetivo. Los rasgos dependen de eso.')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'nav.closeMenu', 'Cerrar menú'),
  ('spa-Latn-ES', 'spa', 'nav.contribute', 'Contribuir'),
  ('spa-Latn-ES', 'spa', 'nav.handbooks', 'Manuales'),
  ('spa-Latn-ES', 'spa', 'nav.home', 'Inicio'),
  ('spa-Latn-ES', 'spa', 'nav.languages', 'Idiomas')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'nav.menu', 'Menú'),
  ('spa-Latn-ES', 'spa', 'nav.openMenu', 'Abrir menú'),
  ('spa-Latn-ES', 'spa', 'nav.searchExpressions', 'Buscar expresiones'),
  ('spa-Latn-ES', 'spa', 'nav.signIn', 'Iniciar sesión'),
  ('spa-Latn-ES', 'spa', 'nav.signOut', 'Cerrar sesión')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'nav.skipToContent', 'Ir al contenido principal'),
  ('spa-Latn-ES', 'spa', 'nav.submitSearch', 'Enviar búsqueda'),
  ('spa-Latn-ES', 'spa', 'nav.switchLanguage', 'Cambiar idioma de la interfaz'),
  ('spa-Latn-ES', 'spa', 'profile.email', 'Correo electrónico'),
  ('spa-Latn-ES', 'spa', 'profile.loadFailed', 'No se pudo cargar el perfil')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'profile.memberSince', 'Miembro desde'),
  ('spa-Latn-ES', 'spa', 'profile.mustLogin', 'Inicia sesión primero'),
  ('spa-Latn-ES', 'spa', 'profile.noActivity', 'No hay actividad'),
  ('spa-Latn-ES', 'spa', 'profile.recentActivity', 'Actividad reciente'),
  ('spa-Latn-ES', 'spa', 'profile.role', 'Rol')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'profile.signOut', 'Cerrar sesión'),
  ('spa-Latn-ES', 'spa', 'profile.title', 'Perfil'),
  ('spa-Latn-ES', 'spa', 'search.alphabetical', 'Alfabético'),
  ('spa-Latn-ES', 'spa', 'search.hint', 'Consejo: la búsqueda actual coincide con el texto de la expresión. La búsqueda semántica llegará más adelante.'),
  ('spa-Latn-ES', 'spa', 'search.languageRequired', 'Selecciona un idioma para buscar')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'search.loadFailed', 'Error al buscar'),
  ('spa-Latn-ES', 'spa', 'search.loadMoreFailed', 'No se pudieron cargar más resultados'),
  ('spa-Latn-ES', 'spa', 'search.newest', 'Más reciente'),
  ('spa-Latn-ES', 'spa', 'search.noResults', 'Sin resultados'),
  ('spa-Latn-ES', 'spa', 'search.placeholder', 'Buscar expresiones…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'search.popular', 'Popular'),
  ('spa-Latn-ES', 'spa', 'search.results', '{count} resultado | {count} resultados'),
  ('spa-Latn-ES', 'spa', 'search.sort', 'Ordenar'),
  ('spa-Latn-ES', 'spa', 'search.title', 'Buscar expresiones'),
  ('spa-Latn-ES', 'spa', 'splitDialog.score', 'puntuación {score}')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'splitDialog.selectMappings', 'Selecciona las relaciones que moverás'),
  ('spa-Latn-ES', 'spa', 'splitDialog.splitting', 'Dividiendo…'),
  ('spa-Latn-ES', 'spa', 'splitDialog.title', 'Dividir expresión'),
  ('spa-Latn-ES', 'spa', 'splitDialog.warning', 'No se copiarán las lecturas, las certificaciones de configuración regional ni los elementos del manual.'),
  ('spa-Latn-ES', 'spa', 'translate.addLocale', 'Añadir un idioma para traducir')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'translate.batchSubmit', 'Enviar {count} traducciones'),
  ('spa-Latn-ES', 'spa', 'translate.candidate', 'Traducción actual'),
  ('spa-Latn-ES', 'spa', 'translate.candidateScore', 'puntuación {score}'),
  ('spa-Latn-ES', 'spa', 'translate.chooseRegistryLanguage', 'Elige un idioma registrado'),
  ('spa-Latn-ES', 'spa', 'translate.coverage', 'Cobertura de traducción')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'translate.displayed', '{count} mostrados'),
  ('spa-Latn-ES', 'spa', 'translate.eyebrow', 'LOCALIZACIÓN COMUNITARIA'),
  ('spa-Latn-ES', 'spa', 'translate.inputPlaceholder', 'Introduce la traducción…'),
  ('spa-Latn-ES', 'spa', 'translate.key', 'Clave del mensaje'),
  ('spa-Latn-ES', 'spa', 'translate.loadFailed', 'No se pudo cargar el área de trabajo de traducción')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'translate.loading', 'Cargando…'),
  ('spa-Latn-ES', 'spa', 'translate.locale', 'Idioma de destino'),
  ('spa-Latn-ES', 'spa', 'translate.localesFailed', 'No se pudo cargar la lista de idiomas'),
  ('spa-Latn-ES', 'spa', 'translate.loginNote', 'Inicia sesión para enviar traducciones; los candidatos se seleccionan por puntuación de relación y se usa el texto de respaldo cuando no hay un candidato positivo.'),
  ('spa-Latn-ES', 'spa', 'translate.noResults', 'No se encontraron textos coincidentes.')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'translate.pendingSubmit', 'Pendiente de enviar'),
  ('spa-Latn-ES', 'spa', 'translate.preview', 'Vista previa'),
  ('spa-Latn-ES', 'spa', 'translate.reference', 'Idioma de referencia'),
  ('spa-Latn-ES', 'spa', 'translate.searchPlaceholder', 'Buscar clave o texto original…'),
  ('spa-Latn-ES', 'spa', 'translate.selectLocale', 'Elegir idioma de traducción')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'translate.source', 'Original en inglés'),
  ('spa-Latn-ES', 'spa', 'translate.sourceAuto', 'Automático'),
  ('spa-Latn-ES', 'spa', 'translate.sourceManual', 'Manual'),
  ('spa-Latn-ES', 'spa', 'translate.sourceSystem', 'Sistema'),
  ('spa-Latn-ES', 'spa', 'translate.start', 'Comenzar')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'translate.statusActive', 'Activo'),
  ('spa-Latn-ES', 'spa', 'translate.statusArchived', 'Archivado'),
  ('spa-Latn-ES', 'spa', 'translate.statusDraft', 'Borrador'),
  ('spa-Latn-ES', 'spa', 'translate.submitFailed', 'Error al enviar'),
  ('spa-Latn-ES', 'spa', 'translate.submitMapping', 'Enviar relación')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'translate.submitted', 'Enviado'),
  ('spa-Latn-ES', 'spa', 'translate.subtitle', 'Ayuda a que el texto de la interfaz de LangMap sea natural y útil.'),
  ('spa-Latn-ES', 'spa', 'translate.title', 'Área de trabajo de traducción'),
  ('spa-Latn-ES', 'spa', 'translate.translateKey', 'Traducir {key}'),
  ('spa-Latn-ES', 'spa', 'translate.translated', 'traducido')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'translate.translation', 'Traducción')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
-- Done