-- AUTO-GENERATED by scripts/i18n/generate-bundle.py. Do not edit.
-- Project: langmap-web; direct UI translation semantic edges.
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'translate.loadFailed', '翻訳ワークベンチを読み込めませんでした'),
  ('jpn-Jpan-JP', 'jpn', 'translate.loading', '読み込み中…'),
  ('jpn-Jpan-JP', 'jpn', 'translate.locale', '対象言語'),
  ('jpn-Jpan-JP', 'jpn', 'translate.localesFailed', '言語リストを読み込めませんでした'),
  ('jpn-Jpan-JP', 'jpn', 'translate.loginNote', 'ログインして翻訳を送信。候補は関係スコアで選択され、適切な候補がない場合はフォールバックが使用されます。')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'translate.noResults', '一致するテキストが見つかりません。'),
  ('jpn-Jpan-JP', 'jpn', 'translate.pendingSubmit', '送信待ち'),
  ('jpn-Jpan-JP', 'jpn', 'translate.preview', 'プレビュー'),
  ('jpn-Jpan-JP', 'jpn', 'translate.reference', '参照言語'),
  ('jpn-Jpan-JP', 'jpn', 'translate.searchPlaceholder', 'キーまたは原文を検索…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'translate.selectLocale', '翻訳言語を選択'),
  ('jpn-Jpan-JP', 'jpn', 'translate.source', '英語原文'),
  ('jpn-Jpan-JP', 'jpn', 'translate.sourceAuto', '自動'),
  ('jpn-Jpan-JP', 'jpn', 'translate.sourceManual', '手動'),
  ('jpn-Jpan-JP', 'jpn', 'translate.sourceSystem', 'システム')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'translate.start', '開始'),
  ('jpn-Jpan-JP', 'jpn', 'translate.statusActive', 'アクティブ'),
  ('jpn-Jpan-JP', 'jpn', 'translate.statusArchived', 'アーカイブ済み'),
  ('jpn-Jpan-JP', 'jpn', 'translate.statusDraft', '下書き'),
  ('jpn-Jpan-JP', 'jpn', 'translate.submitFailed', '送信に失敗しました')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'translate.submitMapping', '関係を送信'),
  ('jpn-Jpan-JP', 'jpn', 'translate.submitted', '送信済み'),
  ('jpn-Jpan-JP', 'jpn', 'translate.subtitle', 'LangMap のインターフェース文言を自然で使いやすくするお手伝いをします。'),
  ('jpn-Jpan-JP', 'jpn', 'translate.title', '翻訳ワークベンチ'),
  ('jpn-Jpan-JP', 'jpn', 'translate.translateKey', '{key} を翻訳')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'translate.translated', '翻訳済み'),
  ('jpn-Jpan-JP', 'jpn', 'translate.translation', '翻訳'),
  ('spa-Latn-ES', 'spa', 'activity.expression', 'Añadió una expresión'),
  ('spa-Latn-ES', 'spa', 'activity.handbook', 'Creó un manual'),
  ('spa-Latn-ES', 'spa', 'activity.mapping', 'Creó una correspondencia')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'activity.voteDown', 'Votó en contra de una correspondencia'),
  ('spa-Latn-ES', 'spa', 'activity.voteUp', 'Votó a favor de una correspondencia'),
  ('spa-Latn-ES', 'spa', 'auth.email', 'Correo electrónico'),
  ('spa-Latn-ES', 'spa', 'auth.haveAccount', '¿Ya tienes cuenta?'),
  ('spa-Latn-ES', 'spa', 'auth.login', 'Iniciar sesión')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'auth.noAccount', '¿No tienes cuenta?'),
  ('spa-Latn-ES', 'spa', 'auth.operationFailed', 'Operación fallida'),
  ('spa-Latn-ES', 'spa', 'auth.password', 'Contraseña'),
  ('spa-Latn-ES', 'spa', 'auth.processing', 'Procesando…'),
  ('spa-Latn-ES', 'spa', 'auth.register', 'Crear cuenta')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'auth.username', 'Nombre de usuario'),
  ('spa-Latn-ES', 'spa', 'autocomplete.noMatch', 'Sin coincidencias'),
  ('spa-Latn-ES', 'spa', 'common.cancel', 'Cancelar'),
  ('spa-Latn-ES', 'spa', 'common.close', 'Cerrar'),
  ('spa-Latn-ES', 'spa', 'common.language', 'Idioma')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'common.languages', 'Idiomas'),
  ('spa-Latn-ES', 'spa', 'common.loading', 'Cargando…'),
  ('spa-Latn-ES', 'spa', 'common.search', 'Buscar'),
  ('spa-Latn-ES', 'spa', 'common.submit', 'Enviar'),
  ('spa-Latn-ES', 'spa', 'components.actualSize', 'Tamaño real 100%')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.anonymous', 'Anónimo'),
  ('spa-Latn-ES', 'spa', 'components.avoidOverlap', 'Organizar para evitar solapamientos'),
  ('spa-Latn-ES', 'spa', 'components.childNodes', '{count} nodos hijos; haz clic para colapsar'),
  ('spa-Latn-ES', 'spa', 'components.cliqueNote', 'Cada arista es una relación directa independiente que se puede votar a favor o en contra; las relaciones con baja puntuación se colapsan.'),
  ('spa-Latn-ES', 'spa', 'components.cliqueTitle', 'Grafo de relaciones a crear')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.closeInfoPanel', 'Cerrar panel de información'),
  ('spa-Latn-ES', 'spa', 'components.collapse', 'Colapsar'),
  ('spa-Latn-ES', 'spa', 'components.collapseBranch', 'Colapsar rama hija'),
  ('spa-Latn-ES', 'spa', 'components.collapseToFirst', 'Colapsar al primer nivel'),
  ('spa-Latn-ES', 'spa', 'components.collapseToolbar', 'Contraer la barra de herramientas del grafo')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.daysAgo', 'Hace {count} días'),
  ('spa-Latn-ES', 'spa', 'components.depth', 'Profundidad {depth}'),
  ('spa-Latn-ES', 'spa', 'components.directMappingList', 'Expresiones con relación directa'),
  ('spa-Latn-ES', 'spa', 'components.downvote', 'Votar en contra'),
  ('spa-Latn-ES', 'spa', 'components.edgeCount', '{count} aristas')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.empty', 'Aún no hay datos'),
  ('spa-Latn-ES', 'spa', 'components.evidence', 'Evidencia'),
  ('spa-Latn-ES', 'spa', 'components.exitFullscreen', 'Salir de pantalla completa'),
  ('spa-Latn-ES', 'spa', 'components.expand', 'Expandir'),
  ('spa-Latn-ES', 'spa', 'components.expandAll', 'Expandir todo')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.expandBranch', 'Expandir rama hija'),
  ('spa-Latn-ES', 'spa', 'components.expandToolbar', 'Expandir la barra de herramientas del grafo'),
  ('spa-Latn-ES', 'spa', 'components.expression', 'Expresión'),
  ('spa-Latn-ES', 'spa', 'components.filterLanguages', 'Filtrar idiomas…'),
  ('spa-Latn-ES', 'spa', 'components.fullscreen', 'Pantalla completa')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.graphLabel', 'Grafo de relaciones de expresiones'),
  ('spa-Latn-ES', 'spa', 'components.graphLoading', 'Cargando grafo…'),
  ('spa-Latn-ES', 'spa', 'components.graphMode', 'Modo grafo'),
  ('spa-Latn-ES', 'spa', 'components.graphStats', '{nodes} nodos mapeados · {edges} relaciones'),
  ('spa-Latn-ES', 'spa', 'components.graphToolbar', 'Barra de herramientas del grafo')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.hierarchyList', 'Lista jerárquica de relaciones'),
  ('spa-Latn-ES', 'spa', 'components.hops', 'Saltos'),
  ('spa-Latn-ES', 'spa', 'components.hoursAgo', 'Hace {count} horas'),
  ('spa-Latn-ES', 'spa', 'components.justNow', 'Ahora mismo'),
  ('spa-Latn-ES', 'spa', 'components.languageLoadFailed', 'No se pudieron cargar los idiomas')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.listMode', 'Modo lista'),
  ('spa-Latn-ES', 'spa', 'components.loadMore', 'Cargar más'),
  ('spa-Latn-ES', 'spa', 'components.loadingRelated', 'Cargando expresiones relacionadas'),
  ('spa-Latn-ES', 'spa', 'components.locale', 'Entorno lingüístico'),
  ('spa-Latn-ES', 'spa', 'components.mapping', 'Relación')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.mappingScore', 'Puntuación de la relación'),
  ('spa-Latn-ES', 'spa', 'components.minutesAgo', 'Hace {count} minutos'),
  ('spa-Latn-ES', 'spa', 'components.moreActions', 'Más acciones'),
  ('spa-Latn-ES', 'spa', 'components.moreMappings', '{count} relaciones más disponibles en el grafo completo'),
  ('spa-Latn-ES', 'spa', 'components.noDirectMappings', 'Aún no hay relaciones directas')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.noExpressions', 'No se encontraron expresiones'),
  ('spa-Latn-ES', 'spa', 'components.nodeCount', '{count} nodos'),
  ('spa-Latn-ES', 'spa', 'components.nodeInfo', 'Información del nodo'),
  ('spa-Latn-ES', 'spa', 'components.otherRelations', 'Otras relaciones'),
  ('spa-Latn-ES', 'spa', 'components.reading', 'Lectura')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.relatedExpressions', 'Expresiones relacionadas'),
  ('spa-Latn-ES', 'spa', 'components.relationCount', '{count} relaciones'),
  ('spa-Latn-ES', 'spa', 'components.removeLanguage', 'Eliminar {code}'),
  ('spa-Latn-ES', 'spa', 'components.resetLayout', 'Restablecer diseño'),
  ('spa-Latn-ES', 'spa', 'components.rootNode', 'Nodo raíz')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.search', 'Buscar'),
  ('spa-Latn-ES', 'spa', 'components.searchExpressions', 'Buscar expresiones…'),
  ('spa-Latn-ES', 'spa', 'components.searching', 'Buscando…'),
  ('spa-Latn-ES', 'spa', 'components.selectNodeHint', 'Selecciona un nodo en el grafo para ver detalles'),
  ('spa-Latn-ES', 'spa', 'components.sourcePath', 'Ruta de origen')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.upvote', 'Votar a favor'),
  ('spa-Latn-ES', 'spa', 'components.viewExpression', 'Ver detalles de la expresión'),
  ('spa-Latn-ES', 'spa', 'components.voteFailed', 'Voto fallido; revertido'),
  ('spa-Latn-ES', 'spa', 'components.zoomIn', 'Acercar'),
  ('spa-Latn-ES', 'spa', 'components.zoomOut', 'Alejar')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'contribute.addExpression', '+ Añadir expresión'),
  ('spa-Latn-ES', 'spa', 'contribute.chooseImage', 'Elegir imagen (máx. 480 px / 100 KB)'),
  ('spa-Latn-ES', 'spa', 'contribute.completeGraph', 'Grafo completo'),
  ('spa-Latn-ES', 'spa', 'contribute.delete', 'Eliminar'),
  ('spa-Latn-ES', 'spa', 'contribute.directMappingCount', '{count} relaciones directas')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'contribute.expression', 'Expresión'),
  ('spa-Latn-ES', 'spa', 'contribute.expressionCount', '{count} expresiones'),
  ('spa-Latn-ES', 'spa', 'contribute.expressionPlaceholder', 'Introduce una expresión…'),
  ('spa-Latn-ES', 'spa', 'contribute.imageTooLarge', 'La imagen comprimida no puede superar los 100 KB'),
  ('spa-Latn-ES', 'spa', 'contribute.imageUploadFailed', 'No se pudo subir la imagen')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'contribute.imageUploading', 'Subiendo…'),
  ('spa-Latn-ES', 'spa', 'contribute.language', 'Idioma'),
  ('spa-Latn-ES', 'spa', 'contribute.lead', 'Envía expresiones que significan lo mismo. El sistema crea una relación directa entre cada par. Las formas flexionadas (plural, pasado, cortesía) se añaden en la página de correspondencias, no aquí.'),
  ('spa-Latn-ES', 'spa', 'contribute.locale', 'Idioma'),
  ('spa-Latn-ES', 'spa', 'contribute.minRows', 'Se requieren al menos 2 filas con idioma y expresión')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'contribute.submit', 'Enviar'),
  ('spa-Latn-ES', 'spa', 'contribute.submitFailed', 'Error al enviar'),
  ('spa-Latn-ES', 'spa', 'contribute.submitting', 'Enviando…'),
  ('spa-Latn-ES', 'spa', 'contribute.tags', 'Etiquetas'),
  ('spa-Latn-ES', 'spa', 'contribute.title', 'Contribución por lotes')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'errors.home', 'Volver al inicio'),
  ('spa-Latn-ES', 'spa', 'errors.loadFailed', 'No se pudo cargar'),
  ('spa-Latn-ES', 'spa', 'errors.pageMissing', 'Página no encontrada'),
  ('spa-Latn-ES', 'spa', 'expression.imageAlt', 'Imagen de la expresión'),
  ('spa-Latn-ES', 'spa', 'feed.all', 'Todo')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'feed.contributeMapping', 'Contribuir una relación →'),
  ('spa-Latn-ES', 'spa', 'feed.hot', 'Popular'),
  ('spa-Latn-ES', 'spa', 'feed.mappingsAndExpressions', 'Relaciones + nuevas expresiones'),
  ('spa-Latn-ES', 'spa', 'feed.missing', '¿No encuentras lo que buscas?'),
  ('spa-Latn-ES', 'spa', 'feed.newContributions', 'Nuevas contribuciones')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'feed.newest', 'Más reciente'),
  ('spa-Latn-ES', 'spa', 'feed.noActivity', 'No hay actividad'),
  ('spa-Latn-ES', 'spa', 'feed.popularMappings', 'Relaciones populares'),
  ('spa-Latn-ES', 'spa', 'feed.ratedThisWeek', 'Por puntuación · esta semana'),
  ('spa-Latn-ES', 'spa', 'feed.subtitle', 'El pulso más reciente del grafo semántico: relaciones populares y nuevas contribuciones.')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'feed.title', 'Actividad'),
  ('spa-Latn-ES', 'spa', 'handbook.addExpression', 'Añadir expresión'),
  ('spa-Latn-ES', 'spa', 'handbook.addSection', 'Añadir sección'),
  ('spa-Latn-ES', 'spa', 'handbook.back', 'Lista de manuales'),
  ('spa-Latn-ES', 'spa', 'handbook.chapter', 'Capítulo {number}')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbook.closeExpressionInfo', 'Cerrar información de la expresión'),
  ('spa-Latn-ES', 'spa', 'handbook.collapsePicker', 'Colapsar'),
  ('spa-Latn-ES', 'spa', 'handbook.deleteSection', 'Eliminar sección'),
  ('spa-Latn-ES', 'spa', 'handbook.edit', 'Editar manual'),
  ('spa-Latn-ES', 'spa', 'handbook.expressionInfo', 'Información de la expresión')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbook.expressionInfoHint', 'El idioma, la región y la fuente de la expresión aparecerán aquí.'),
  ('spa-Latn-ES', 'spa', 'handbook.helpful', '¿Te resultó útil este manual?'),
  ('spa-Latn-ES', 'spa', 'handbook.inspectorFailed', 'No se pudo cargar la expresión'),
  ('spa-Latn-ES', 'spa', 'handbook.loadFailed', 'No se pudo cargar'),
  ('spa-Latn-ES', 'spa', 'handbook.locale', 'Idioma')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbook.moveDown', 'Mover abajo'),
  ('spa-Latn-ES', 'spa', 'handbook.moveSectionDown', 'Mover sección abajo'),
  ('spa-Latn-ES', 'spa', 'handbook.moveSectionUp', 'Mover sección arriba'),
  ('spa-Latn-ES', 'spa', 'handbook.moveUp', 'Mover arriba'),
  ('spa-Latn-ES', 'spa', 'handbook.private', 'Privado')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbook.public', 'Público'),
  ('spa-Latn-ES', 'spa', 'handbook.publish', 'Publicar'),
  ('spa-Latn-ES', 'spa', 'handbook.region', 'Región'),
  ('spa-Latn-ES', 'spa', 'handbook.relationsFailed', 'No se pudieron cargar las expresiones relacionadas'),
  ('spa-Latn-ES', 'spa', 'handbook.removeExpression', 'Eliminar {text}')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbook.saveDraft', 'Guardar borrador'),
  ('spa-Latn-ES', 'spa', 'handbook.saving', 'Guardando…'),
  ('spa-Latn-ES', 'spa', 'handbook.sectionTitle', 'Título de la sección'),
  ('spa-Latn-ES', 'spa', 'handbook.selectExpression', 'Seleccionar una expresión'),
  ('spa-Latn-ES', 'spa', 'handbook.source', 'Fuente')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbook.sourceAi', 'IA'),
  ('spa-Latn-ES', 'spa', 'handbook.sourceAuthority', 'Autoridad'),
  ('spa-Latn-ES', 'spa', 'handbook.sourceUser', 'Usuario'),
  ('spa-Latn-ES', 'spa', 'handbook.titlePlaceholder', 'Título del manual'),
  ('spa-Latn-ES', 'spa', 'handbook.toc', 'Contenido')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbook.viewFullGraph', 'Ver grafo completo de relaciones'),
  ('spa-Latn-ES', 'spa', 'handbook.visibility', 'Visibilidad'),
  ('spa-Latn-ES', 'spa', 'handbooks.create', 'Nuevo manual'),
  ('spa-Latn-ES', 'spa', 'handbooks.loadFailed', 'No se pudieron cargar los manuales'),
  ('spa-Latn-ES', 'spa', 'handbooks.newest', 'Más reciente')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbooks.noResults', 'No se encontraron manuales'),
  ('spa-Latn-ES', 'spa', 'handbooks.popular', 'Popular'),
  ('spa-Latn-ES', 'spa', 'handbooks.searchPlaceholder', 'Buscar manuales…'),
  ('spa-Latn-ES', 'spa', 'handbooks.sections', 'secciones'),
  ('spa-Latn-ES', 'spa', 'handbooks.title', 'Manuales')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.back', 'Atrás'),
  ('spa-Latn-ES', 'spa', 'languageCreate.cancel', 'Cancelar'),
  ('spa-Latn-ES', 'spa', 'languageCreate.close', 'Cerrar'),
  ('spa-Latn-ES', 'spa', 'languageCreate.create', 'Crear idioma'),
  ('spa-Latn-ES', 'spa', 'languageCreate.createFailed', 'Error al crear el idioma')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.creating', 'Creando…'),
  ('spa-Latn-ES', 'spa', 'languageCreate.errorDescription', 'Introduce una descripción'),
  ('spa-Latn-ES', 'spa', 'languageCreate.errorGlottolog', 'Elige una coincidencia Glottolog o selecciona «sin coincidencia»'),
  ('spa-Latn-ES', 'spa', 'languageCreate.errorName', 'Introduce un nombre de idioma'),
  ('spa-Latn-ES', 'spa', 'languageCreate.errorReason', 'Selecciona un motivo para la creación solo comunitaria')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.errorTag', 'Introduce una subetiqueta de idioma para continuar'),
  ('spa-Latn-ES', 'spa', 'languageCreate.glottologCandidates', '{count} candidato(s) encontrado(s)'),
  ('spa-Latn-ES', 'spa', 'languageCreate.glottologChoose', 'Elige una coincidencia o indica que no hay entrada adecuada'),
  ('spa-Latn-ES', 'spa', 'languageCreate.glottologExactMatch', 'Elegir este candidato'),
  ('spa-Latn-ES', 'spa', 'languageCreate.glottologLevelDialect', 'dialecto')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.glottologLevelLanguage', 'idioma'),
  ('spa-Latn-ES', 'spa', 'languageCreate.glottologNoMatch', 'Glottolog no tiene una entrada adecuada'),
  ('spa-Latn-ES', 'spa', 'languageCreate.glottologSearchPlaceholder', 'Buscar en Glottolog…'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataDescription', 'Descripción'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataDescriptionPlaceholder', 'Describe este idioma o variedad…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataName', 'Nombre'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataNameEn', 'Nombre en inglés'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataReason', '¿Por qué falta este idioma en Glottolog?'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataReasonCommunity', 'Uso específico de la comunidad'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataReasonEmerging', 'Variante emergente')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataReasonMissing', 'Falta en Glottolog'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataReasonOther', 'Otro'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataReasonPlaceholder', 'Selecciona un motivo…'),
  ('spa-Latn-ES', 'spa', 'languageCreate.next', 'Siguiente'),
  ('spa-Latn-ES', 'spa', 'languageCreate.optional', 'Opcional')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.previewCanonicalCode', 'Código canónico'),
  ('spa-Latn-ES', 'spa', 'languageCreate.previewExisting', 'Este idioma ya existe'),
  ('spa-Latn-ES', 'spa', 'languageCreate.previewExistingAction', 'Usar idioma existente'),
  ('spa-Latn-ES', 'spa', 'languageCreate.previewTitle', 'Crear idioma'),
  ('spa-Latn-ES', 'spa', 'languageCreate.previewWarnings', 'Advertencias')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.provisionalTag', 'Etiqueta provisional'),
  ('spa-Latn-ES', 'spa', 'languageCreate.requiredHint', 'Los campos con * son obligatorios'),
  ('spa-Latn-ES', 'spa', 'languageCreate.stepGlottolog', 'Coincidencia Glottolog'),
  ('spa-Latn-ES', 'spa', 'languageCreate.stepMetadata', 'Metadatos'),
  ('spa-Latn-ES', 'spa', 'languageCreate.stepPreview', 'Vista previa y crear')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.stepTag', 'Etiqueta de idioma'),
  ('spa-Latn-ES', 'spa', 'languageCreate.subtagLanguage', 'Idioma'),
  ('spa-Latn-ES', 'spa', 'languageCreate.subtagRegion', 'Región'),
  ('spa-Latn-ES', 'spa', 'languageCreate.subtagScript', 'Escritura'),
  ('spa-Latn-ES', 'spa', 'languageCreate.subtagSearch', 'Buscar subetiquetas…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.subtagVariant', 'Variante'),
  ('spa-Latn-ES', 'spa', 'languageCreate.variantRemoved', '1 variante eliminada'),
  ('spa-Latn-ES', 'spa', 'languageCreate.variantsRemoved', '{count} variante(s) eliminada(s)'),
  ('spa-Latn-ES', 'spa', 'languageDetail.allOthers', 'Todos'),
  ('spa-Latn-ES', 'spa', 'languageDetail.allVariants', 'Todas las variantes')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageDetail.alphabetical', 'Alfabético'),
  ('spa-Latn-ES', 'spa', 'languageDetail.back', 'Idiomas'),
  ('spa-Latn-ES', 'spa', 'languageDetail.expressions', 'Expresiones'),
  ('spa-Latn-ES', 'spa', 'languageDetail.latest', 'Más reciente'),
  ('spa-Latn-ES', 'spa', 'languageDetail.loadFailed', 'No se pudo cargar')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageDetail.mapped', 'Mapeado'),
  ('spa-Latn-ES', 'spa', 'languageDetail.noResults', 'No se encontraron expresiones'),
  ('spa-Latn-ES', 'spa', 'languageDetail.otherLabel', 'Otro'),
  ('spa-Latn-ES', 'spa', 'languageDetail.popular', 'Popular'),
  ('spa-Latn-ES', 'spa', 'languageDetail.regionalForms', 'Formas regionales')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageDetail.representativeCities', 'Ciudades representativas'),
  ('spa-Latn-ES', 'spa', 'languageDetail.representativeCitiesNote', 'Estas ciudades son solo orientativas'),
  ('spa-Latn-ES', 'spa', 'languageDetail.scripts.Hans', 'Chino simplificado'),
  ('spa-Latn-ES', 'spa', 'languageDetail.scripts.Hant', 'Chino tradicional'),
  ('spa-Latn-ES', 'spa', 'languageDetail.scripts.Jpan', 'Japonés')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageDetail.scripts.Latn', 'Latino'),
  ('spa-Latn-ES', 'spa', 'languageDetail.searchPlaceholder', 'Buscar expresiones…'),
  ('spa-Latn-ES', 'spa', 'languageDetail.variantLabel', 'Escritura'),
  ('spa-Latn-ES', 'spa', 'languagePicker.clear', 'Limpiar selección'),
  ('spa-Latn-ES', 'spa', 'languagePicker.createLanguage', 'Crear nuevo idioma o variedad')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languagePicker.noResults', 'No hay idiomas coincidentes'),
  ('spa-Latn-ES', 'spa', 'languagePicker.placeholder', 'Buscar idiomas…'),
  ('spa-Latn-ES', 'spa', 'languageSwitcher.browserSuggested', 'Sugerido por tu navegador'),
  ('spa-Latn-ES', 'spa', 'languageSwitcher.helpTranslate', 'Ayuda a traducir LangMap'),
  ('spa-Latn-ES', 'spa', 'languageSwitcher.noResults', 'No hay idiomas coincidentes')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageSwitcher.recent', 'Idiomas recientes'),
  ('spa-Latn-ES', 'spa', 'languagesPage.addLanguage', 'Añadir idioma'),
  ('spa-Latn-ES', 'spa', 'languagesPage.expressionCount', 'Expresiones'),
  ('spa-Latn-ES', 'spa', 'languagesPage.languageCount', 'Idiomas'),
  ('spa-Latn-ES', 'spa', 'languagesPage.loadFailed', 'No se pudieron cargar los idiomas')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languagesPage.noResults', 'No se encontraron idiomas'),
  ('spa-Latn-ES', 'spa', 'languagesPage.searchPlaceholder', 'Buscar idiomas…'),
  ('spa-Latn-ES', 'spa', 'languagesPage.sortAlphabetical', 'A–Z'),
  ('spa-Latn-ES', 'spa', 'languagesPage.sortCount', 'Cantidad'),
  ('spa-Latn-ES', 'spa', 'languagesPage.subtitle', 'Explorar expresiones y relaciones entre todos los idiomas')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languagesPage.title', 'Idiomas'),
  ('spa-Latn-ES', 'spa', 'localeCreate.codePreviewEmpty', 'Completa los campos obligatorios para previsualizar el código'),
  ('spa-Latn-ES', 'spa', 'localeCreate.create', 'Crear locale'),
  ('spa-Latn-ES', 'spa', 'localeCreate.createFailed', 'Error al crear el locale'),
  ('spa-Latn-ES', 'spa', 'localeCreate.englishName', 'Nombre en inglés')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'localeCreate.heading', 'Crear locale de idioma'),
  ('spa-Latn-ES', 'spa', 'localeCreate.latitude', 'Latitud'),
  ('spa-Latn-ES', 'spa', 'localeCreate.localName', 'Nombre local'),
  ('spa-Latn-ES', 'spa', 'localeCreate.longitude', 'Longitud'),
  ('spa-Latn-ES', 'spa', 'localeCreate.place', 'Segmentos de lugar')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'localeCreate.placePlaceholder', 'Quanzhou_Nanan'),
  ('spa-Latn-ES', 'spa', 'localeCreate.region', 'Región'),
  ('spa-Latn-ES', 'spa', 'localeCreate.regionPlaceholder', 'Código ISO 3166-1'),
  ('spa-Latn-ES', 'spa', 'localeCreate.script', 'Escritura'),
  ('spa-Latn-ES', 'spa', 'localeCreate.scriptPlaceholder', 'Código ISO 15924')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mapLens.anchor', 'Ancla'),
  ('spa-Latn-ES', 'spa', 'mapLens.back', 'Volver a la relación'),
  ('spa-Latn-ES', 'spa', 'mapLens.languages', '{count} idiomas'),
  ('spa-Latn-ES', 'spa', 'mapLens.loadFailed', 'No se pudo cargar'),
  ('spa-Latn-ES', 'spa', 'mapLens.members', 'Miembros de la relación')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
-- Done