-- AUTO-GENERATED by scripts/i18n/generate-bundle.py. Do not edit.
-- Project: langmap-web; direct UI translation semantic edges.
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'languageDetail.allVariants', '全部變體'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.alphabetical', '依字母排序'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.back', '語言'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.expressions', '詞句'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.latest', '最新')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'languageDetail.loadFailed', '無法載入'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.mapped', '已對應'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.noResults', '找不到詞句'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.otherLabel', '其他'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.popular', '熱門')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'languageDetail.regionalForms', '地區形式'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.representativeCities', '代表城市'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.representativeCitiesNote', '這些城市僅供參考'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.scripts.Hans', '简体'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.scripts.Hant', '傳承體')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'languageDetail.scripts.Jpan', '日文'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.scripts.Latn', '拉丁'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.searchPlaceholder', '搜尋詞句…'),
  ('cmn-Hant-TW', 'cmn', 'languageDetail.variantLabel', '文字'),
  ('cmn-Hant-TW', 'cmn', 'languagePicker.clear', '清除選擇')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'languagePicker.createLanguage', '建立新語言或變體'),
  ('cmn-Hant-TW', 'cmn', 'languagePicker.noResults', '無符合語言'),
  ('cmn-Hant-TW', 'cmn', 'languagePicker.placeholder', '搜尋語言…'),
  ('cmn-Hant-TW', 'cmn', 'languageSwitcher.browserSuggested', '瀏覽器推薦'),
  ('cmn-Hant-TW', 'cmn', 'languageSwitcher.helpTranslate', '協助翻譯 LangMap')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'languageSwitcher.noResults', '無符合的語言'),
  ('cmn-Hant-TW', 'cmn', 'languageSwitcher.recent', '最近使用的語言'),
  ('cmn-Hant-TW', 'cmn', 'languagesPage.addLanguage', '新增語言'),
  ('cmn-Hant-TW', 'cmn', 'languagesPage.expressionCount', '詞句'),
  ('cmn-Hant-TW', 'cmn', 'languagesPage.languageCount', '語言')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'languagesPage.loadFailed', '無法載入語言'),
  ('cmn-Hant-TW', 'cmn', 'languagesPage.noResults', '找不到語言'),
  ('cmn-Hant-TW', 'cmn', 'languagesPage.searchPlaceholder', '搜尋語言…'),
  ('cmn-Hant-TW', 'cmn', 'languagesPage.sortAlphabetical', 'A–Z'),
  ('cmn-Hant-TW', 'cmn', 'languagesPage.sortCount', '依數量')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'languagesPage.subtitle', '瀏覽所有語言的詞句與對應關係'),
  ('cmn-Hant-TW', 'cmn', 'languagesPage.title', '語言'),
  ('cmn-Hant-TW', 'cmn', 'localeCreate.codePreviewEmpty', '填寫必填欄位以預覽代碼'),
  ('cmn-Hant-TW', 'cmn', 'localeCreate.create', '建立語言環境'),
  ('cmn-Hant-TW', 'cmn', 'localeCreate.createFailed', '無法建立語言環境')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'localeCreate.englishName', '英文名稱'),
  ('cmn-Hant-TW', 'cmn', 'localeCreate.heading', '建立語言環境'),
  ('cmn-Hant-TW', 'cmn', 'localeCreate.latitude', '緯度'),
  ('cmn-Hant-TW', 'cmn', 'localeCreate.localName', '當地名稱'),
  ('cmn-Hant-TW', 'cmn', 'localeCreate.longitude', '經度')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'localeCreate.place', '地名片段'),
  ('cmn-Hant-TW', 'cmn', 'localeCreate.placePlaceholder', '泉州_南安'),
  ('cmn-Hant-TW', 'cmn', 'localeCreate.region', '地區'),
  ('cmn-Hant-TW', 'cmn', 'localeCreate.regionPlaceholder', 'ISO 3166-1 代碼'),
  ('cmn-Hant-TW', 'cmn', 'localeCreate.script', '文字')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'localeCreate.scriptPlaceholder', 'ISO 15924 代碼'),
  ('cmn-Hant-TW', 'cmn', 'mapLens.anchor', '錨點'),
  ('cmn-Hant-TW', 'cmn', 'mapLens.back', '回到對應'),
  ('cmn-Hant-TW', 'cmn', 'mapLens.languages', '{count} 種語言'),
  ('cmn-Hant-TW', 'cmn', 'mapLens.loadFailed', '無法載入')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'mapLens.members', '對應成員'),
  ('cmn-Hant-TW', 'cmn', 'mapLens.noData', '此詞句無地理分佈資料'),
  ('cmn-Hant-TW', 'cmn', 'mapLens.regions', '{count} 個地區'),
  ('cmn-Hant-TW', 'cmn', 'mapLens.title', '詞句分佈'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.addAndMap', '新增並建立對應')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.addExpression', '新增詞句'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.addFailed', '無法新增詞句'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.adding', '新增中…'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.authority', '權威'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.breadcrumb', '麵包屑')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.closeQuickAdd', '關閉快速新增'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.contribute', '貢獻對應'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.direct', '直接對應'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.enterRequired', '請輸入詞句與語言代碼'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.expression', '詞句')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.expressionPlaceholder', '輸入詞句…'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.graph', '圖譜'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.home', '首頁'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.hops', '跳數'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.indirect', '間接')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.languageCode', '語言代碼'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.languageCodePlaceholder', '例如 en / cmn-Hant'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.list', '列表'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.loadFailed', '無法載入'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.mappingSet', '對應集合')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.noMappings', '尚無對應'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.optional', '選填'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.quickAdd', '快速新增詞句'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.quickAddLead', '新增詞句並直接對應到目前詞句。'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.region', '地區')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.user', '使用者'),
  ('cmn-Hant-TW', 'cmn', 'mappingDetail.viewMap', '在地圖上檢視此詞句'),
  ('cmn-Hant-TW', 'cmn', 'morphology.addFormLink', '新增詞形關聯'),
  ('cmn-Hant-TW', 'cmn', 'morphology.class.adjective', '形容詞'),
  ('cmn-Hant-TW', 'cmn', 'morphology.class.noun', '名詞')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'morphology.class.verb', '動詞'),
  ('cmn-Hant-TW', 'cmn', 'morphology.dictionaryForm', '辭書形'),
  ('cmn-Hant-TW', 'cmn', 'morphology.empty', '尚無詞形關聯'),
  ('cmn-Hant-TW', 'cmn', 'morphology.formOfAria', '{lemma} 的變化形：{features}'),
  ('cmn-Hant-TW', 'cmn', 'morphology.hideForm', '收起表單')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'morphology.loadFailed', '無法載入詞形'),
  ('cmn-Hant-TW', 'cmn', 'morphology.markAsForm', '標為某個詞的變化形…'),
  ('cmn-Hant-TW', 'cmn', 'morphology.noLanguageFeatures', '這個詞類沒有預設特徵。仍可先儲存關聯，或改顯示全部特徵。'),
  ('cmn-Hant-TW', 'cmn', 'morphology.pickFeatures', '特徵'),
  ('cmn-Hant-TW', 'cmn', 'morphology.pickFeaturesHint', '選填。只顯示此語言、此詞類常用的特徵。')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'morphology.saved', '已儲存詞形關聯'),
  ('cmn-Hant-TW', 'cmn', 'morphology.saving', '儲存中…'),
  ('cmn-Hant-TW', 'cmn', 'morphology.searchLemma', '搜尋同一語言的辭書形'),
  ('cmn-Hant-TW', 'cmn', 'morphology.searchLemmaLabel', '辭書形'),
  ('cmn-Hant-TW', 'cmn', 'morphology.showAllFeatures', '顯示全部特徵')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'morphology.submit', '儲存詞形關聯'),
  ('cmn-Hant-TW', 'cmn', 'morphology.submitFailed', '無法儲存詞形關聯'),
  ('cmn-Hant-TW', 'cmn', 'morphology.title', '詞形變化'),
  ('cmn-Hant-TW', 'cmn', 'morphology.wordClass', '詞類'),
  ('cmn-Hant-TW', 'cmn', 'morphology.wordClassHint', '先選名詞、動詞或形容詞，再顯示對應特徵。')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'nav.closeMenu', '關閉選單'),
  ('cmn-Hant-TW', 'cmn', 'nav.contribute', '貢獻'),
  ('cmn-Hant-TW', 'cmn', 'nav.handbooks', '手冊'),
  ('cmn-Hant-TW', 'cmn', 'nav.home', '首頁'),
  ('cmn-Hant-TW', 'cmn', 'nav.languages', '語言')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'nav.menu', '選單'),
  ('cmn-Hant-TW', 'cmn', 'nav.openMenu', '開啟選單'),
  ('cmn-Hant-TW', 'cmn', 'nav.searchExpressions', '搜尋詞句'),
  ('cmn-Hant-TW', 'cmn', 'nav.signIn', '登入'),
  ('cmn-Hant-TW', 'cmn', 'nav.signOut', '登出')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'nav.skipToContent', '跳至主要內容'),
  ('cmn-Hant-TW', 'cmn', 'nav.submitSearch', '送出搜尋'),
  ('cmn-Hant-TW', 'cmn', 'nav.switchLanguage', '切換介面語言'),
  ('cmn-Hant-TW', 'cmn', 'profile.email', '電子郵件'),
  ('cmn-Hant-TW', 'cmn', 'profile.loadFailed', '無法載入個人資料')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'profile.memberSince', '加入時間'),
  ('cmn-Hant-TW', 'cmn', 'profile.mustLogin', '請先登入'),
  ('cmn-Hant-TW', 'cmn', 'profile.noActivity', '暫無活動記錄'),
  ('cmn-Hant-TW', 'cmn', 'profile.recentActivity', '最近活動'),
  ('cmn-Hant-TW', 'cmn', 'profile.role', '角色')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'profile.signOut', '登出'),
  ('cmn-Hant-TW', 'cmn', 'profile.title', '個人資料'),
  ('cmn-Hant-TW', 'cmn', 'search.alphabetical', '依字母順序'),
  ('cmn-Hant-TW', 'cmn', 'search.hint', '提示：目前搜尋比對詞句原文。語意搜尋即將推出。'),
  ('cmn-Hant-TW', 'cmn', 'search.loadFailed', '搜尋失敗')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'search.loadMoreFailed', '無法載入更多結果'),
  ('cmn-Hant-TW', 'cmn', 'search.newest', '最新'),
  ('cmn-Hant-TW', 'cmn', 'search.noResults', '找不到結果'),
  ('cmn-Hant-TW', 'cmn', 'search.placeholder', '搜尋詞句…'),
  ('cmn-Hant-TW', 'cmn', 'search.popular', '熱門')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'search.results', '{count} 個結果'),
  ('cmn-Hant-TW', 'cmn', 'search.sort', '排序'),
  ('cmn-Hant-TW', 'cmn', 'search.title', '搜尋詞句'),
  ('cmn-Hant-TW', 'cmn', 'translate.addLocale', '新增要翻譯的語言'),
  ('cmn-Hant-TW', 'cmn', 'translate.batchSubmit', '提交 {count} 筆翻譯')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'translate.candidate', '目前翻譯'),
  ('cmn-Hant-TW', 'cmn', 'translate.candidateScore', '分數 {score}'),
  ('cmn-Hant-TW', 'cmn', 'translate.chooseRegistryLanguage', '選擇已註冊的語言'),
  ('cmn-Hant-TW', 'cmn', 'translate.coverage', '翻譯涵蓋率'),
  ('cmn-Hant-TW', 'cmn', 'translate.displayed', '顯示 {count} 筆')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'translate.eyebrow', '社群本地化'),
  ('cmn-Hant-TW', 'cmn', 'translate.inputPlaceholder', '輸入翻譯…'),
  ('cmn-Hant-TW', 'cmn', 'translate.key', '訊息鍵'),
  ('cmn-Hant-TW', 'cmn', 'translate.loadFailed', '無法載入翻譯工作台'),
  ('cmn-Hant-TW', 'cmn', 'translate.loading', '載入中…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'translate.locale', '目標語言'),
  ('cmn-Hant-TW', 'cmn', 'translate.localesFailed', '無法載入語言列表'),
  ('cmn-Hant-TW', 'cmn', 'translate.loginNote', '登入後可提交翻譯；候選翻譯依對應分數排序，無正分候選時使用備用文字。'),
  ('cmn-Hant-TW', 'cmn', 'translate.noResults', '找不到相符文字。'),
  ('cmn-Hant-TW', 'cmn', 'translate.pendingSubmit', '待提交')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'translate.preview', '預覽'),
  ('cmn-Hant-TW', 'cmn', 'translate.reference', '參考語言'),
  ('cmn-Hant-TW', 'cmn', 'translate.searchPlaceholder', '搜尋鍵名或原文…'),
  ('cmn-Hant-TW', 'cmn', 'translate.selectLocale', '選擇翻譯語言'),
  ('cmn-Hant-TW', 'cmn', 'translate.source', '英文原文')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'translate.sourceAuto', '自動'),
  ('cmn-Hant-TW', 'cmn', 'translate.sourceManual', '手動'),
  ('cmn-Hant-TW', 'cmn', 'translate.sourceSystem', '系統'),
  ('cmn-Hant-TW', 'cmn', 'translate.start', '開始'),
  ('cmn-Hant-TW', 'cmn', 'translate.statusActive', '已啟用')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'translate.statusArchived', '已封存'),
  ('cmn-Hant-TW', 'cmn', 'translate.statusDraft', '草稿'),
  ('cmn-Hant-TW', 'cmn', 'translate.submitFailed', '提交失敗'),
  ('cmn-Hant-TW', 'cmn', 'translate.submitMapping', '提交對應'),
  ('cmn-Hant-TW', 'cmn', 'translate.submitted', '已提交')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'translate.subtitle', '幫助讓 LangMap 介面文字更自然、更實用。'),
  ('cmn-Hant-TW', 'cmn', 'translate.title', '翻譯工作台'),
  ('cmn-Hant-TW', 'cmn', 'translate.translateKey', '翻譯 {key}'),
  ('cmn-Hant-TW', 'cmn', 'translate.translated', '已翻譯'),
  ('cmn-Hant-TW', 'cmn', 'translate.translation', '翻譯')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'activity.expression', '表現を追加しました'),
  ('jpn-Jpan-JP', 'jpn', 'activity.handbook', 'ハンドブックを作成しました'),
  ('jpn-Jpan-JP', 'jpn', 'activity.mapping', '対応付けを作成しました'),
  ('jpn-Jpan-JP', 'jpn', 'activity.voteDown', '対応付けに反対しました'),
  ('jpn-Jpan-JP', 'jpn', 'activity.voteUp', '対応付けに賛成しました')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'auth.email', 'メールアドレス'),
  ('jpn-Jpan-JP', 'jpn', 'auth.haveAccount', 'すでにアカウントをお持ちですか？'),
  ('jpn-Jpan-JP', 'jpn', 'auth.login', 'ログイン'),
  ('jpn-Jpan-JP', 'jpn', 'auth.noAccount', 'アカウントをお持ちでないですか？'),
  ('jpn-Jpan-JP', 'jpn', 'auth.operationFailed', '操作に失敗しました')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'auth.password', 'パスワード'),
  ('jpn-Jpan-JP', 'jpn', 'auth.processing', '処理中…'),
  ('jpn-Jpan-JP', 'jpn', 'auth.register', 'アカウント作成'),
  ('jpn-Jpan-JP', 'jpn', 'auth.username', 'ユーザー名'),
  ('jpn-Jpan-JP', 'jpn', 'autocomplete.noMatch', '一致する項目がありません')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'common.cancel', 'キャンセル'),
  ('jpn-Jpan-JP', 'jpn', 'common.close', '閉じる'),
  ('jpn-Jpan-JP', 'jpn', 'common.language', '言語'),
  ('jpn-Jpan-JP', 'jpn', 'common.languages', '言語'),
  ('jpn-Jpan-JP', 'jpn', 'common.loading', '読み込み中…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'common.search', '検索'),
  ('jpn-Jpan-JP', 'jpn', 'common.submit', '送信'),
  ('jpn-Jpan-JP', 'jpn', 'components.actualSize', '実際のサイズ 100%'),
  ('jpn-Jpan-JP', 'jpn', 'components.anonymous', '匿名'),
  ('jpn-Jpan-JP', 'jpn', 'components.childNodes', '{count} 個の子ノード；クリックして折りたたむ')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'components.cliqueNote', '各エッジは独立した直接関係で、賛成・反対の投票が可能です。低スコアの関係は自動的に折りたたまれます。'),
  ('jpn-Jpan-JP', 'jpn', 'components.cliqueTitle', '作成する関係グラフ'),
  ('jpn-Jpan-JP', 'jpn', 'components.closeInfoPanel', '情報パネルを閉じる'),
  ('jpn-Jpan-JP', 'jpn', 'components.collapse', '折りたたむ'),
  ('jpn-Jpan-JP', 'jpn', 'components.collapseBranch', '子ノードを折りたたむ')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'components.collapseToFirst', '最初の階層に折りたたむ'),
  ('jpn-Jpan-JP', 'jpn', 'components.daysAgo', '{count} 日前'),
  ('jpn-Jpan-JP', 'jpn', 'components.depth', '深さ {depth}'),
  ('jpn-Jpan-JP', 'jpn', 'components.directMappingList', '直接関係のある表現'),
  ('jpn-Jpan-JP', 'jpn', 'components.downvote', '反対')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'components.edgeCount', '{count} エッジ'),
  ('jpn-Jpan-JP', 'jpn', 'components.empty', 'データはまだありません'),
  ('jpn-Jpan-JP', 'jpn', 'components.evidence', '根拠'),
  ('jpn-Jpan-JP', 'jpn', 'components.exitFullscreen', '全画面を終了'),
  ('jpn-Jpan-JP', 'jpn', 'components.expand', '展開')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'components.expandAll', 'すべて展開'),
  ('jpn-Jpan-JP', 'jpn', 'components.expandBranch', '子ノードを展開'),
  ('jpn-Jpan-JP', 'jpn', 'components.expression', '表現'),
  ('jpn-Jpan-JP', 'jpn', 'components.filterLanguages', '言語をフィルター…'),
  ('jpn-Jpan-JP', 'jpn', 'components.fullscreen', '全画面')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'components.graphLabel', '表現関係グラフ'),
  ('jpn-Jpan-JP', 'jpn', 'components.graphLoading', 'グラフを読み込み中…'),
  ('jpn-Jpan-JP', 'jpn', 'components.graphMode', 'グラフモード'),
  ('jpn-Jpan-JP', 'jpn', 'components.graphStats', '{nodes} 個のマッピングノード · {edges} 件の関係'),
  ('jpn-Jpan-JP', 'jpn', 'components.graphToolbar', 'グラフツールバー')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'components.hierarchyList', '関係階層リスト'),
  ('jpn-Jpan-JP', 'jpn', 'components.hops', 'ホップ数'),
  ('jpn-Jpan-JP', 'jpn', 'components.hoursAgo', '{count} 時間前'),
  ('jpn-Jpan-JP', 'jpn', 'components.justNow', 'たった今'),
  ('jpn-Jpan-JP', 'jpn', 'components.languageLoadFailed', '言語を読み込めませんでした')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'components.listMode', 'リストモード'),
  ('jpn-Jpan-JP', 'jpn', 'components.loadMore', 'さらに読み込む'),
  ('jpn-Jpan-JP', 'jpn', 'components.loadingRelated', '関連表現を読み込み中'),
  ('jpn-Jpan-JP', 'jpn', 'components.locale', '言語環境'),
  ('jpn-Jpan-JP', 'jpn', 'components.mapping', '関係')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'components.mappingScore', '関係スコア'),
  ('jpn-Jpan-JP', 'jpn', 'components.minutesAgo', '{count} 分前'),
  ('jpn-Jpan-JP', 'jpn', 'components.moreActions', 'その他の操作'),
  ('jpn-Jpan-JP', 'jpn', 'components.moreMappings', '完全なグラフにはさらに {count} 件の関係があります'),
  ('jpn-Jpan-JP', 'jpn', 'components.noDirectMappings', '直接関係はまだありません')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'components.noExpressions', '表現が見つかりません'),
  ('jpn-Jpan-JP', 'jpn', 'components.nodeCount', '{count} ノード'),
  ('jpn-Jpan-JP', 'jpn', 'components.nodeInfo', 'ノード情報'),
  ('jpn-Jpan-JP', 'jpn', 'components.otherRelations', 'その他の関係'),
  ('jpn-Jpan-JP', 'jpn', 'components.reading', '読み方')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'components.relatedExpressions', '関連表現'),
  ('jpn-Jpan-JP', 'jpn', 'components.relationCount', '{count} 件の関係'),
  ('jpn-Jpan-JP', 'jpn', 'components.removeLanguage', '{code} を削除'),
  ('jpn-Jpan-JP', 'jpn', 'components.resetLayout', 'レイアウトをリセット'),
  ('jpn-Jpan-JP', 'jpn', 'components.rootNode', 'ルートノード')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'components.search', '検索'),
  ('jpn-Jpan-JP', 'jpn', 'components.searchExpressions', '表現を検索…'),
  ('jpn-Jpan-JP', 'jpn', 'components.searching', '検索中…'),
  ('jpn-Jpan-JP', 'jpn', 'components.selectNodeHint', 'グラフ内のノードを選択して詳細を表示'),
  ('jpn-Jpan-JP', 'jpn', 'components.sourcePath', '元の経路')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'components.upvote', '賛成'),
  ('jpn-Jpan-JP', 'jpn', 'components.viewExpression', '表現の詳細を表示'),
  ('jpn-Jpan-JP', 'jpn', 'components.voteFailed', '投票に失敗しました。元に戻しました'),
  ('jpn-Jpan-JP', 'jpn', 'components.zoomIn', '拡大'),
  ('jpn-Jpan-JP', 'jpn', 'components.zoomOut', '縮小')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'contribute.addExpression', '+ 表現を追加'),
  ('jpn-Jpan-JP', 'jpn', 'contribute.completeGraph', '完全グラフ'),
  ('jpn-Jpan-JP', 'jpn', 'contribute.delete', '削除'),
  ('jpn-Jpan-JP', 'jpn', 'contribute.directMappingCount', '{count} 件の直接関係'),
  ('jpn-Jpan-JP', 'jpn', 'contribute.expression', '表現')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'contribute.expressionCount', '{count} 件の表現'),
  ('jpn-Jpan-JP', 'jpn', 'contribute.expressionPlaceholder', '表現を入力…'),
  ('jpn-Jpan-JP', 'jpn', 'contribute.language', '言語'),
  ('jpn-Jpan-JP', 'jpn', 'contribute.lead', '同じ意味の表現を送信します。システムは各ペアに直接関係を作ります。複数形・過去形・丁寧形などの語形変化は、表現の対応ページで追加してください。'),
  ('jpn-Jpan-JP', 'jpn', 'contribute.locale', '言語')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'contribute.minRows', '言語と表現を入力した行が少なくとも2行必要です'),
  ('jpn-Jpan-JP', 'jpn', 'contribute.submit', '送信'),
  ('jpn-Jpan-JP', 'jpn', 'contribute.submitFailed', '送信に失敗しました'),
  ('jpn-Jpan-JP', 'jpn', 'contribute.submitting', '送信中…'),
  ('jpn-Jpan-JP', 'jpn', 'contribute.tags', 'タグ')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'contribute.title', '一括投稿'),
  ('jpn-Jpan-JP', 'jpn', 'errors.home', 'ホームに戻る'),
  ('jpn-Jpan-JP', 'jpn', 'errors.loadFailed', '読み込めませんでした'),
  ('jpn-Jpan-JP', 'jpn', 'errors.pageMissing', 'ページが見つかりません'),
  ('jpn-Jpan-JP', 'jpn', 'expression.imageAlt', '表現の画像')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'feed.all', 'すべて'),
  ('jpn-Jpan-JP', 'jpn', 'feed.contributeMapping', '関係を投稿する →'),
  ('jpn-Jpan-JP', 'jpn', 'feed.hot', '人気'),
  ('jpn-Jpan-JP', 'jpn', 'feed.mappingsAndExpressions', '関係 + 新しい表現'),
  ('jpn-Jpan-JP', 'jpn', 'feed.missing', '必要なものが見つかりませんか？')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'feed.newContributions', '新しい貢献'),
  ('jpn-Jpan-JP', 'jpn', 'feed.newest', '最新'),
  ('jpn-Jpan-JP', 'jpn', 'feed.noActivity', 'アクティビティはありません'),
  ('jpn-Jpan-JP', 'jpn', 'feed.popularMappings', '人気の関係'),
  ('jpn-Jpan-JP', 'jpn', 'feed.ratedThisWeek', 'スコア順 · 今週')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'feed.subtitle', '意味グラフの最新情報 — 人気の関係と新しい貢献。'),
  ('jpn-Jpan-JP', 'jpn', 'feed.title', 'アクティビティ'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.addExpression', '表現を追加'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.addSection', 'セクションを追加'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.back', 'ハンドブック一覧')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
-- Done