-- AUTO-GENERATED by scripts/i18n/generate-bundle.py. Do not edit.
-- Project: langmap-web; direct UI translation semantic edges.
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'handbook.chapter', '第 {number} 章'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.closeExpressionInfo', '表現情報を閉じる'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.collapsePicker', '折りたたむ'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.deleteSection', 'セクションを削除'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.edit', 'ハンドブックを編集')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'handbook.expressionInfo', '表現情報'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.expressionInfoHint', '表現の言語、地域、ソースがここに表示されます。'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.helpful', 'このハンドブックは役に立ちましたか？'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.inspectorFailed', '表現を読み込めませんでした'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.loadFailed', '読み込めませんでした')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'handbook.locale', '言語'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.moveDown', '下に移動'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.moveSectionDown', 'セクションを下に移動'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.moveSectionUp', 'セクションを上に移動'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.moveUp', '上に移動')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'handbook.private', '非公開'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.public', '公開'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.publish', '公開'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.region', '地域'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.relationsFailed', '関連表現を読み込めませんでした')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'handbook.removeExpression', '{text} を削除'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.saveDraft', '下書きを保存'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.saving', '保存中…'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.sectionTitle', 'セクションタイトル'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.selectExpression', '表現を選択')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'handbook.source', 'ソース'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.sourceAi', 'AI'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.sourceAuthority', '権威'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.sourceUser', 'ユーザー'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.titlePlaceholder', 'ハンドブックのタイトル')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'handbook.toc', '目次'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.viewFullGraph', '完全な関係グラフを表示'),
  ('jpn-Jpan-JP', 'jpn', 'handbook.visibility', '公開設定'),
  ('jpn-Jpan-JP', 'jpn', 'handbooks.create', '新しいハンドブック'),
  ('jpn-Jpan-JP', 'jpn', 'handbooks.loadFailed', 'ハンドブックを読み込めませんでした')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'handbooks.newest', '最新'),
  ('jpn-Jpan-JP', 'jpn', 'handbooks.noResults', 'ハンドブックが見つかりません'),
  ('jpn-Jpan-JP', 'jpn', 'handbooks.popular', '人気'),
  ('jpn-Jpan-JP', 'jpn', 'handbooks.searchPlaceholder', 'ハンドブックを検索…'),
  ('jpn-Jpan-JP', 'jpn', 'handbooks.sections', 'セクション')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'handbooks.title', 'ハンドブック'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.back', '戻る'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.cancel', 'キャンセル'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.close', '閉じる'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.create', '言語を作成')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.createFailed', '言語の作成に失敗しました'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.creating', '作成中…'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.errorDescription', '説明を入力してください'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.errorGlottolog', 'Glottolog の一致を選択するか、「一致なし」を選択'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.errorName', '言語名を入力してください')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.errorReason', 'コミュニティのみ作成の理由を選択してください'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.errorTag', '続行するには言語サブタグを入力してください'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.glottologCandidates', '{count} 件の候補が見つかりました'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.glottologChoose', '一致を選択するか、適切な項目がないことを指定'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.glottologExactMatch', 'この候補に一致')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.glottologLevelDialect', '方言'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.glottologLevelLanguage', '言語'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.glottologNoMatch', 'Glottolog に適切な項目がありません'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.glottologSearchPlaceholder', 'Glottolog を検索…'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.metadataDescription', '説明')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.metadataDescriptionPlaceholder', 'この言語または変種を説明…'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.metadataName', '名前'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.metadataNameEn', '英語名'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.metadataReason', 'この言語が Glottolog にない理由は？'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.metadataReasonCommunity', 'コミュニティ固有の用法')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.metadataReasonEmerging', '新しい変種'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.metadataReasonMissing', 'Glottolog に未収録'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.metadataReasonOther', 'その他'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.metadataReasonPlaceholder', '理由を選択…'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.next', '次へ')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.optional', '任意'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.previewCanonicalCode', '正規コード'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.previewExisting', 'この言語はすでに存在します'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.previewExistingAction', '既存の言語を使用'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.previewTitle', '言語を作成')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.previewWarnings', '警告'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.provisionalTag', '暫定タグ'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.requiredHint', '* の項目は必須です'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.stepGlottolog', 'Glottolog マッチ'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.stepMetadata', 'メタデータ')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.stepPreview', 'プレビューと作成'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.stepTag', '言語タグ'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.subtagLanguage', '言語'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.subtagRegion', '地域'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.subtagScript', '文字')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.subtagSearch', 'サブタグを検索…'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.subtagVariant', '変種'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.variantRemoved', '1 件の変種を削除'),
  ('jpn-Jpan-JP', 'jpn', 'languageCreate.variantsRemoved', '{count} 件の変種を削除'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.allOthers', 'すべて')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.allVariants', 'すべての変種'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.alphabetical', 'アルファベット順'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.back', '言語'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.expressions', '表現'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.latest', '最新')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.loadFailed', '読み込めませんでした'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.mapped', 'マッピング済み'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.noResults', '表現が見つかりません'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.otherLabel', 'その他'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.popular', '人気')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.regionalForms', '地域別の形式'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.representativeCities', '代表的な都市'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.representativeCitiesNote', 'これらの都市は参考情報です'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.scripts.Hans', '簡体字'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.scripts.Hant', '繁体字')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.scripts.Jpan', '日本語'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.scripts.Latn', 'ラテン文字'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.searchPlaceholder', '表現を検索…'),
  ('jpn-Jpan-JP', 'jpn', 'languageDetail.variantLabel', '文字'),
  ('jpn-Jpan-JP', 'jpn', 'languagePicker.clear', '選択をクリア')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languagePicker.createLanguage', '新しい言語または変種を作成'),
  ('jpn-Jpan-JP', 'jpn', 'languagePicker.noResults', '一致する言語がありません'),
  ('jpn-Jpan-JP', 'jpn', 'languagePicker.placeholder', '言語を検索…'),
  ('jpn-Jpan-JP', 'jpn', 'languageSwitcher.browserSuggested', 'ブラウザの推奨'),
  ('jpn-Jpan-JP', 'jpn', 'languageSwitcher.helpTranslate', 'LangMap の翻訳に協力する')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languageSwitcher.noResults', '一致する言語がありません'),
  ('jpn-Jpan-JP', 'jpn', 'languageSwitcher.recent', '最近使用した言語'),
  ('jpn-Jpan-JP', 'jpn', 'languagesPage.addLanguage', '言語を追加'),
  ('jpn-Jpan-JP', 'jpn', 'languagesPage.expressionCount', '表現'),
  ('jpn-Jpan-JP', 'jpn', 'languagesPage.languageCount', '言語')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languagesPage.loadFailed', '言語を読み込めませんでした'),
  ('jpn-Jpan-JP', 'jpn', 'languagesPage.noResults', '言語が見つかりません'),
  ('jpn-Jpan-JP', 'jpn', 'languagesPage.searchPlaceholder', '言語を検索…'),
  ('jpn-Jpan-JP', 'jpn', 'languagesPage.sortAlphabetical', 'A–Z'),
  ('jpn-Jpan-JP', 'jpn', 'languagesPage.sortCount', '件数')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'languagesPage.subtitle', 'すべての言語の表現と関係を探索'),
  ('jpn-Jpan-JP', 'jpn', 'languagesPage.title', '言語'),
  ('jpn-Jpan-JP', 'jpn', 'localeCreate.codePreviewEmpty', '必須項目を入力するとコードをプレビューできます'),
  ('jpn-Jpan-JP', 'jpn', 'localeCreate.create', 'ロケールを作成'),
  ('jpn-Jpan-JP', 'jpn', 'localeCreate.createFailed', 'ロケールを作成できませんでした')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'localeCreate.englishName', '英語名'),
  ('jpn-Jpan-JP', 'jpn', 'localeCreate.heading', '言語ロケールを作成'),
  ('jpn-Jpan-JP', 'jpn', 'localeCreate.latitude', '緯度'),
  ('jpn-Jpan-JP', 'jpn', 'localeCreate.localName', '現地名'),
  ('jpn-Jpan-JP', 'jpn', 'localeCreate.longitude', '経度')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'localeCreate.place', '地名セグメント'),
  ('jpn-Jpan-JP', 'jpn', 'localeCreate.placePlaceholder', '泉州_南安'),
  ('jpn-Jpan-JP', 'jpn', 'localeCreate.region', '地域'),
  ('jpn-Jpan-JP', 'jpn', 'localeCreate.regionPlaceholder', 'ISO 3166-1 コード'),
  ('jpn-Jpan-JP', 'jpn', 'localeCreate.script', '文字')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'localeCreate.scriptPlaceholder', 'ISO 15924 コード'),
  ('jpn-Jpan-JP', 'jpn', 'mapLens.anchor', 'アンカー'),
  ('jpn-Jpan-JP', 'jpn', 'mapLens.back', '関係に戻る'),
  ('jpn-Jpan-JP', 'jpn', 'mapLens.languages', '{count} 言語'),
  ('jpn-Jpan-JP', 'jpn', 'mapLens.loadFailed', '読み込めませんでした')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'mapLens.members', '関係メンバー'),
  ('jpn-Jpan-JP', 'jpn', 'mapLens.noData', 'この詞句の地理的分布データはありません'),
  ('jpn-Jpan-JP', 'jpn', 'mapLens.regions', '{count} 地域'),
  ('jpn-Jpan-JP', 'jpn', 'mapLens.title', '詞句の分布'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.addAndMap', '追加して関係を作成')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.addExpression', '表現を追加'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.addFailed', '表現を追加できませんでした'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.adding', '追加中…'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.authority', '権威'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.breadcrumb', 'パンくず')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.closeQuickAdd', 'クイック追加を閉じる'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.contribute', '関係を投稿'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.direct', '直接関係'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.enterRequired', '表現と言語コードを入力してください'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.expression', '表現')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.expressionPlaceholder', '表現を入力…'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.graph', 'グラフ'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.home', 'ホーム'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.hops', 'ホップ数'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.indirect', '間接')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.languageCode', '言語コード'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.languageCodePlaceholder', '例：en / cmn-Hant'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.list', 'リスト'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.loadFailed', '読み込めませんでした'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.mappingSet', '関係セット')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.noMappings', 'まだ関係がありません'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.optional', '任意'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.quickAdd', '表現をすばやく追加'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.quickAddLead', '表現を追加し、現在の表現に直接マップします。'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.region', '地域')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.user', 'ユーザー'),
  ('jpn-Jpan-JP', 'jpn', 'mappingDetail.viewMap', 'この詞句を地図で表示'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.addFormLink', '語形リンクを追加'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.class.adjective', '形容詞'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.class.noun', '名詞')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'morphology.class.verb', '動詞'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.dictionaryForm', '辞書形'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.empty', '語形リンクはまだありません'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.formOfAria', '{lemma} の変化形：{features}'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.hideForm', 'フォームを閉じる')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'morphology.loadFailed', '語形を読み込めませんでした'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.markAsForm', 'ある語の変化形として記録…'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.noLanguageFeatures', 'この品詞の既定特徴はありません。リンクだけ保存するか、すべての特徴を表示できます。'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.pickFeatures', '特徴'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.pickFeaturesHint', '任意。この言語・この品詞でよく使う特徴だけ表示します。')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'morphology.saved', '語形リンクを保存しました'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.saving', '保存中…'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.searchLemma', '同じ言語の辞書形を検索'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.searchLemmaLabel', '辞書形'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.showAllFeatures', 'すべての特徴を表示')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'morphology.submit', '語形リンクを保存'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.submitFailed', '語形リンクを保存できませんでした'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.title', '語形変化'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.wordClass', '品詞'),
  ('jpn-Jpan-JP', 'jpn', 'morphology.wordClassHint', '先に名詞・動詞・形容詞を選ぶと、対応する特徴だけ出ます。')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'nav.closeMenu', 'メニューを閉じる'),
  ('jpn-Jpan-JP', 'jpn', 'nav.contribute', '貢献'),
  ('jpn-Jpan-JP', 'jpn', 'nav.handbooks', 'ハンドブック'),
  ('jpn-Jpan-JP', 'jpn', 'nav.home', 'ホーム'),
  ('jpn-Jpan-JP', 'jpn', 'nav.languages', '言語')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'nav.menu', 'メニュー'),
  ('jpn-Jpan-JP', 'jpn', 'nav.openMenu', 'メニューを開く'),
  ('jpn-Jpan-JP', 'jpn', 'nav.searchExpressions', '表現を検索'),
  ('jpn-Jpan-JP', 'jpn', 'nav.signIn', 'ログイン'),
  ('jpn-Jpan-JP', 'jpn', 'nav.signOut', 'ログアウト')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'nav.skipToContent', 'メインコンテンツへ移動'),
  ('jpn-Jpan-JP', 'jpn', 'nav.submitSearch', '検索を実行'),
  ('jpn-Jpan-JP', 'jpn', 'nav.switchLanguage', 'インターフェース言語を切り替え'),
  ('jpn-Jpan-JP', 'jpn', 'profile.email', 'メールアドレス'),
  ('jpn-Jpan-JP', 'jpn', 'profile.loadFailed', 'プロフィールを読み込めませんでした')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'profile.memberSince', '登録日'),
  ('jpn-Jpan-JP', 'jpn', 'profile.mustLogin', 'ログインしてください'),
  ('jpn-Jpan-JP', 'jpn', 'profile.noActivity', 'アクティビティはありません'),
  ('jpn-Jpan-JP', 'jpn', 'profile.recentActivity', '最近のアクティビティ'),
  ('jpn-Jpan-JP', 'jpn', 'profile.role', '役割')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'profile.signOut', 'ログアウト'),
  ('jpn-Jpan-JP', 'jpn', 'profile.title', 'プロフィール'),
  ('jpn-Jpan-JP', 'jpn', 'search.alphabetical', 'アルファベット順'),
  ('jpn-Jpan-JP', 'jpn', 'search.hint', 'ヒント：現在の検索は表現テキストに一致します。意味検索は後日提供予定です。'),
  ('jpn-Jpan-JP', 'jpn', 'search.loadFailed', '検索に失敗しました')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'search.loadMoreFailed', '続きの結果を読み込めませんでした'),
  ('jpn-Jpan-JP', 'jpn', 'search.newest', '最新'),
  ('jpn-Jpan-JP', 'jpn', 'search.noResults', '結果が見つかりません'),
  ('jpn-Jpan-JP', 'jpn', 'search.placeholder', '表現を検索…'),
  ('jpn-Jpan-JP', 'jpn', 'search.popular', '人気')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'search.results', '{count} 件の結果'),
  ('jpn-Jpan-JP', 'jpn', 'search.sort', '並び替え'),
  ('jpn-Jpan-JP', 'jpn', 'search.title', '表現を検索'),
  ('jpn-Jpan-JP', 'jpn', 'translate.addLocale', '翻訳する言語を追加'),
  ('jpn-Jpan-JP', 'jpn', 'translate.batchSubmit', '{count} 件の翻訳を送信')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'translate.candidate', '現在の翻訳'),
  ('jpn-Jpan-JP', 'jpn', 'translate.candidateScore', 'スコア {score}'),
  ('jpn-Jpan-JP', 'jpn', 'translate.chooseRegistryLanguage', '登録済みの言語を選択'),
  ('jpn-Jpan-JP', 'jpn', 'translate.coverage', '翻訳カバレッジ'),
  ('jpn-Jpan-JP', 'jpn', 'translate.displayed', '{count} 件表示')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'translate.eyebrow', 'コミュニティ翻訳'),
  ('jpn-Jpan-JP', 'jpn', 'translate.inputPlaceholder', '翻訳を入力…'),
  ('jpn-Jpan-JP', 'jpn', 'translate.key', 'メッセージキー'),
  ('jpn-Jpan-JP', 'jpn', 'translate.loadFailed', '翻訳ワークベンチを読み込めませんでした'),
  ('jpn-Jpan-JP', 'jpn', 'translate.loading', '読み込み中…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'translate.locale', '対象言語'),
  ('jpn-Jpan-JP', 'jpn', 'translate.localesFailed', '言語リストを読み込めませんでした'),
  ('jpn-Jpan-JP', 'jpn', 'translate.loginNote', 'ログインして翻訳を送信。候補は関係スコアで選択され、適切な候補がない場合はフォールバックが使用されます。'),
  ('jpn-Jpan-JP', 'jpn', 'translate.noResults', '一致するテキストが見つかりません。'),
  ('jpn-Jpan-JP', 'jpn', 'translate.pendingSubmit', '送信待ち')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'translate.preview', 'プレビュー'),
  ('jpn-Jpan-JP', 'jpn', 'translate.reference', '参照言語'),
  ('jpn-Jpan-JP', 'jpn', 'translate.searchPlaceholder', 'キーまたは原文を検索…'),
  ('jpn-Jpan-JP', 'jpn', 'translate.selectLocale', '翻訳言語を選択'),
  ('jpn-Jpan-JP', 'jpn', 'translate.source', '英語原文')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'translate.sourceAuto', '自動'),
  ('jpn-Jpan-JP', 'jpn', 'translate.sourceManual', '手動'),
  ('jpn-Jpan-JP', 'jpn', 'translate.sourceSystem', 'システム'),
  ('jpn-Jpan-JP', 'jpn', 'translate.start', '開始'),
  ('jpn-Jpan-JP', 'jpn', 'translate.statusActive', 'アクティブ')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'translate.statusArchived', 'アーカイブ済み'),
  ('jpn-Jpan-JP', 'jpn', 'translate.statusDraft', '下書き'),
  ('jpn-Jpan-JP', 'jpn', 'translate.submitFailed', '送信に失敗しました'),
  ('jpn-Jpan-JP', 'jpn', 'translate.submitMapping', '関係を送信'),
  ('jpn-Jpan-JP', 'jpn', 'translate.submitted', '送信済み')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('jpn-Jpan-JP', 'jpn', 'translate.subtitle', 'LangMap のインターフェース文言を自然で使いやすくするお手伝いをします。'),
  ('jpn-Jpan-JP', 'jpn', 'translate.title', '翻訳ワークベンチ'),
  ('jpn-Jpan-JP', 'jpn', 'translate.translateKey', '{key} を翻訳'),
  ('jpn-Jpan-JP', 'jpn', 'translate.translated', '翻訳済み'),
  ('jpn-Jpan-JP', 'jpn', 'translate.translation', '翻訳')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'activity.expression', 'Añadió una expresión'),
  ('spa-Latn-ES', 'spa', 'activity.handbook', 'Creó un manual'),
  ('spa-Latn-ES', 'spa', 'activity.mapping', 'Creó una correspondencia'),
  ('spa-Latn-ES', 'spa', 'activity.voteDown', 'Votó en contra de una correspondencia'),
  ('spa-Latn-ES', 'spa', 'activity.voteUp', 'Votó a favor de una correspondencia')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'auth.email', 'Correo electrónico'),
  ('spa-Latn-ES', 'spa', 'auth.haveAccount', '¿Ya tienes cuenta?'),
  ('spa-Latn-ES', 'spa', 'auth.login', 'Iniciar sesión'),
  ('spa-Latn-ES', 'spa', 'auth.noAccount', '¿No tienes cuenta?'),
  ('spa-Latn-ES', 'spa', 'auth.operationFailed', 'Operación fallida')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'auth.password', 'Contraseña'),
  ('spa-Latn-ES', 'spa', 'auth.processing', 'Procesando…'),
  ('spa-Latn-ES', 'spa', 'auth.register', 'Crear cuenta'),
  ('spa-Latn-ES', 'spa', 'auth.username', 'Nombre de usuario'),
  ('spa-Latn-ES', 'spa', 'autocomplete.noMatch', 'Sin coincidencias')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'common.cancel', 'Cancelar'),
  ('spa-Latn-ES', 'spa', 'common.close', 'Cerrar'),
  ('spa-Latn-ES', 'spa', 'common.language', 'Idioma'),
  ('spa-Latn-ES', 'spa', 'common.languages', 'Idiomas'),
  ('spa-Latn-ES', 'spa', 'common.loading', 'Cargando…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'common.search', 'Buscar'),
  ('spa-Latn-ES', 'spa', 'common.submit', 'Enviar'),
  ('spa-Latn-ES', 'spa', 'components.actualSize', 'Tamaño real 100%'),
  ('spa-Latn-ES', 'spa', 'components.anonymous', 'Anónimo'),
  ('spa-Latn-ES', 'spa', 'components.childNodes', '{count} nodos hijos; haz clic para colapsar')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.cliqueNote', 'Cada arista es una relación directa independiente que se puede votar a favor o en contra; las relaciones con baja puntuación se colapsan.'),
  ('spa-Latn-ES', 'spa', 'components.cliqueTitle', 'Grafo de relaciones a crear'),
  ('spa-Latn-ES', 'spa', 'components.closeInfoPanel', 'Cerrar panel de información'),
  ('spa-Latn-ES', 'spa', 'components.collapse', 'Colapsar'),
  ('spa-Latn-ES', 'spa', 'components.collapseBranch', 'Colapsar rama hija')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
-- Done