-- AUTO-GENERATED by scripts/i18n/generate-bundle.py. Do not edit.
-- Project: langmap-web; direct UI translation semantic edges.
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'mappingDetail.optional', '选填'),
  ('cmn-Hans-CN', 'cmn', 'mappingDetail.quickAdd', '快速新增词句'),
  ('cmn-Hans-CN', 'cmn', 'mappingDetail.quickAddLead', '新增词句并直接映射到当前词句。'),
  ('cmn-Hans-CN', 'cmn', 'mappingDetail.region', '地区'),
  ('cmn-Hans-CN', 'cmn', 'mappingDetail.splitExpression', '拆分词句')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'mappingDetail.splitFailed', '无法拆分词句'),
  ('cmn-Hans-CN', 'cmn', 'mappingDetail.splitLoadFailed', '无法加载要拆分的对应关系'),
  ('cmn-Hans-CN', 'cmn', 'mappingDetail.targetLanguage', '目标语言'),
  ('cmn-Hans-CN', 'cmn', 'mappingDetail.user', '用户'),
  ('cmn-Hans-CN', 'cmn', 'mappingDetail.viewMap', '在地图上查看此词句')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'morphology.addFormLink', '新增词形关联'),
  ('cmn-Hans-CN', 'cmn', 'morphology.class.adjective', '形容词'),
  ('cmn-Hans-CN', 'cmn', 'morphology.class.noun', '名词'),
  ('cmn-Hans-CN', 'cmn', 'morphology.class.verb', '动词'),
  ('cmn-Hans-CN', 'cmn', 'morphology.dictionaryForm', '辞典形')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'morphology.empty', '尚无词形关联'),
  ('cmn-Hans-CN', 'cmn', 'morphology.formOfAria', '{lemma} 的变化形：{features}'),
  ('cmn-Hans-CN', 'cmn', 'morphology.hideForm', '收起表单'),
  ('cmn-Hans-CN', 'cmn', 'morphology.loadFailed', '无法加载词形'),
  ('cmn-Hans-CN', 'cmn', 'morphology.markAsForm', '标为某个词的变化形…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'morphology.noLanguageFeatures', '这个词类没有预设特征。仍可先保存关联，或改显示全部特征。'),
  ('cmn-Hans-CN', 'cmn', 'morphology.pickFeatures', '特征'),
  ('cmn-Hans-CN', 'cmn', 'morphology.pickFeaturesHint', '选填。只显示此语言、此词类常用的特征。'),
  ('cmn-Hans-CN', 'cmn', 'morphology.saved', '已保存词形关联'),
  ('cmn-Hans-CN', 'cmn', 'morphology.saving', '保存中…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'morphology.searchLemma', '搜索同一语言的辞典形'),
  ('cmn-Hans-CN', 'cmn', 'morphology.searchLemmaLabel', '辞典形'),
  ('cmn-Hans-CN', 'cmn', 'morphology.showAllFeatures', '显示全部特征'),
  ('cmn-Hans-CN', 'cmn', 'morphology.submit', '保存词形关联'),
  ('cmn-Hans-CN', 'cmn', 'morphology.submitFailed', '无法保存词形关联')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'morphology.title', '词形变化'),
  ('cmn-Hans-CN', 'cmn', 'morphology.wordClass', '词类'),
  ('cmn-Hans-CN', 'cmn', 'morphology.wordClassHint', '先选名词、动词或形容词，再显示对应特征。'),
  ('cmn-Hans-CN', 'cmn', 'nav.closeMenu', '关闭菜单'),
  ('cmn-Hans-CN', 'cmn', 'nav.contribute', '贡献')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'nav.handbooks', '手册'),
  ('cmn-Hans-CN', 'cmn', 'nav.home', '首页'),
  ('cmn-Hans-CN', 'cmn', 'nav.languages', '语言'),
  ('cmn-Hans-CN', 'cmn', 'nav.menu', '菜单'),
  ('cmn-Hans-CN', 'cmn', 'nav.openMenu', '打开菜单')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'nav.searchExpressions', '搜索词句'),
  ('cmn-Hans-CN', 'cmn', 'nav.signIn', '登录'),
  ('cmn-Hans-CN', 'cmn', 'nav.signOut', '退出登录'),
  ('cmn-Hans-CN', 'cmn', 'nav.skipToContent', '跳转到主要内容'),
  ('cmn-Hans-CN', 'cmn', 'nav.submitSearch', '提交搜索')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'nav.switchLanguage', '切换界面语言'),
  ('cmn-Hans-CN', 'cmn', 'profile.email', '邮箱'),
  ('cmn-Hans-CN', 'cmn', 'profile.loadFailed', '无法加载个人资料'),
  ('cmn-Hans-CN', 'cmn', 'profile.memberSince', '加入时间'),
  ('cmn-Hans-CN', 'cmn', 'profile.mustLogin', '请先登录')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'profile.noActivity', '暂无活动记录'),
  ('cmn-Hans-CN', 'cmn', 'profile.recentActivity', '最近活动'),
  ('cmn-Hans-CN', 'cmn', 'profile.role', '角色'),
  ('cmn-Hans-CN', 'cmn', 'profile.signOut', '退出登录'),
  ('cmn-Hans-CN', 'cmn', 'profile.title', '个人资料')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'search.alphabetical', '按字母顺序'),
  ('cmn-Hans-CN', 'cmn', 'search.hint', '提示：目前搜索匹配词句原文。翻译（语义）搜索即将推出。'),
  ('cmn-Hans-CN', 'cmn', 'search.languageRequired', '请选择要搜索的语言'),
  ('cmn-Hans-CN', 'cmn', 'search.loadFailed', '搜索失败'),
  ('cmn-Hans-CN', 'cmn', 'search.loadMoreFailed', '无法加载更多结果')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'search.newest', '最新'),
  ('cmn-Hans-CN', 'cmn', 'search.noResults', '未找到结果'),
  ('cmn-Hans-CN', 'cmn', 'search.placeholder', '搜索词句…'),
  ('cmn-Hans-CN', 'cmn', 'search.popular', '热门'),
  ('cmn-Hans-CN', 'cmn', 'search.results', '{count} 个结果')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'search.sort', '排序'),
  ('cmn-Hans-CN', 'cmn', 'search.title', '搜索词句'),
  ('cmn-Hans-CN', 'cmn', 'splitDialog.score', '分数 {score}'),
  ('cmn-Hans-CN', 'cmn', 'splitDialog.selectMappings', '选择要移动的对应关系'),
  ('cmn-Hans-CN', 'cmn', 'splitDialog.splitting', '拆分中…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'splitDialog.title', '拆分词句'),
  ('cmn-Hans-CN', 'cmn', 'splitDialog.warning', '读音、语言环境认证与手册项目不会被复制。'),
  ('cmn-Hans-CN', 'cmn', 'translate.addLocale', '添加要翻译的语言'),
  ('cmn-Hans-CN', 'cmn', 'translate.batchSubmit', '提交 {count} 条翻译'),
  ('cmn-Hans-CN', 'cmn', 'translate.candidate', '当前翻译')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'translate.candidateScore', '分数 {score}'),
  ('cmn-Hans-CN', 'cmn', 'translate.chooseRegistryLanguage', '选择已注册的语言'),
  ('cmn-Hans-CN', 'cmn', 'translate.coverage', '翻译覆盖率'),
  ('cmn-Hans-CN', 'cmn', 'translate.displayed', '显示 {count} 条'),
  ('cmn-Hans-CN', 'cmn', 'translate.eyebrow', '社区本地化')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'translate.inputPlaceholder', '输入翻译…'),
  ('cmn-Hans-CN', 'cmn', 'translate.key', '消息键'),
  ('cmn-Hans-CN', 'cmn', 'translate.loadFailed', '无法加载翻译工作台'),
  ('cmn-Hans-CN', 'cmn', 'translate.loading', '加载中…'),
  ('cmn-Hans-CN', 'cmn', 'translate.locale', '目标语言')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'translate.localesFailed', '无法加载语言列表'),
  ('cmn-Hans-CN', 'cmn', 'translate.loginNote', '登录后可提交翻译；候选翻译按映射分数排序，无正分候选时使用回退文本。'),
  ('cmn-Hans-CN', 'cmn', 'translate.noResults', '未找到匹配文本。'),
  ('cmn-Hans-CN', 'cmn', 'translate.pendingSubmit', '待提交'),
  ('cmn-Hans-CN', 'cmn', 'translate.preview', '预览')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'translate.reference', '参考语言'),
  ('cmn-Hans-CN', 'cmn', 'translate.searchPlaceholder', '搜索键名或原文…'),
  ('cmn-Hans-CN', 'cmn', 'translate.selectLocale', '选择翻译语言'),
  ('cmn-Hans-CN', 'cmn', 'translate.source', '英文原文'),
  ('cmn-Hans-CN', 'cmn', 'translate.sourceAuto', '自动')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'translate.sourceManual', '手动'),
  ('cmn-Hans-CN', 'cmn', 'translate.sourceSystem', '系统'),
  ('cmn-Hans-CN', 'cmn', 'translate.start', '开始'),
  ('cmn-Hans-CN', 'cmn', 'translate.statusActive', '已启用'),
  ('cmn-Hans-CN', 'cmn', 'translate.statusArchived', '已归档')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'translate.statusDraft', '草稿'),
  ('cmn-Hans-CN', 'cmn', 'translate.submitFailed', '提交失败'),
  ('cmn-Hans-CN', 'cmn', 'translate.submitMapping', '提交映射'),
  ('cmn-Hans-CN', 'cmn', 'translate.submitted', '已提交'),
  ('cmn-Hans-CN', 'cmn', 'translate.subtitle', '帮助让 LangMap 界面文本更自然、更实用。')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hans-CN', 'cmn', 'translate.title', '翻译工作台'),
  ('cmn-Hans-CN', 'cmn', 'translate.translateKey', '翻译 {key}'),
  ('cmn-Hans-CN', 'cmn', 'translate.translated', '已翻译'),
  ('cmn-Hans-CN', 'cmn', 'translate.translation', '翻译'),
  ('cmn-Hant-TW', 'cmn', 'activity.expression', '新增了詞句')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'activity.handbook', '建立了手冊'),
  ('cmn-Hant-TW', 'cmn', 'activity.mapping', '完成了對應'),
  ('cmn-Hant-TW', 'cmn', 'activity.voteDown', '反對了一條對應'),
  ('cmn-Hant-TW', 'cmn', 'activity.voteUp', '贊成了一條對應'),
  ('cmn-Hant-TW', 'cmn', 'auth.email', '電子郵件')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'auth.haveAccount', '已經有帳號了？'),
  ('cmn-Hant-TW', 'cmn', 'auth.login', '登入'),
  ('cmn-Hant-TW', 'cmn', 'auth.noAccount', '還沒有帳號？'),
  ('cmn-Hant-TW', 'cmn', 'auth.operationFailed', '操作失敗'),
  ('cmn-Hant-TW', 'cmn', 'auth.password', '密碼')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'auth.processing', '處理中…'),
  ('cmn-Hant-TW', 'cmn', 'auth.register', '建立帳號'),
  ('cmn-Hant-TW', 'cmn', 'auth.username', '使用者名稱'),
  ('cmn-Hant-TW', 'cmn', 'autocomplete.noMatch', '無符合項目'),
  ('cmn-Hant-TW', 'cmn', 'common.cancel', '取消')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'common.close', '關閉'),
  ('cmn-Hant-TW', 'cmn', 'common.language', '語言'),
  ('cmn-Hant-TW', 'cmn', 'common.languages', '語言'),
  ('cmn-Hant-TW', 'cmn', 'common.loading', '載入中…'),
  ('cmn-Hant-TW', 'cmn', 'common.search', '搜尋')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'common.submit', '提交'),
  ('cmn-Hant-TW', 'cmn', 'components.actualSize', '實際尺寸 100%'),
  ('cmn-Hant-TW', 'cmn', 'components.anonymous', '匿名'),
  ('cmn-Hant-TW', 'cmn', 'components.avoidOverlap', '排列以避免重疊'),
  ('cmn-Hant-TW', 'cmn', 'components.childNodes', '{count} 個子節點；點選收合')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'components.cliqueNote', '每條邊皆為可投票的獨立直接對應；低分對應自動收合'),
  ('cmn-Hant-TW', 'cmn', 'components.cliqueTitle', '待建立的對應圖譜'),
  ('cmn-Hant-TW', 'cmn', 'components.closeInfoPanel', '關閉資訊面板'),
  ('cmn-Hant-TW', 'cmn', 'components.collapse', '收合'),
  ('cmn-Hant-TW', 'cmn', 'components.collapseBranch', '收合子分支')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'components.collapseToFirst', '收合至第一層'),
  ('cmn-Hant-TW', 'cmn', 'components.collapseToolbar', '收合圖譜工具列'),
  ('cmn-Hant-TW', 'cmn', 'components.daysAgo', '{count} 天前'),
  ('cmn-Hant-TW', 'cmn', 'components.depth', '深度 {depth}'),
  ('cmn-Hant-TW', 'cmn', 'components.directMappingList', '直接對應詞句')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'components.downvote', '倒讚'),
  ('cmn-Hant-TW', 'cmn', 'components.edgeCount', '{count} 條邊'),
  ('cmn-Hant-TW', 'cmn', 'components.empty', '目前沒有資料'),
  ('cmn-Hant-TW', 'cmn', 'components.evidence', '證據'),
  ('cmn-Hant-TW', 'cmn', 'components.exitFullscreen', '退出全螢幕')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'components.expand', '展開'),
  ('cmn-Hant-TW', 'cmn', 'components.expandAll', '全部展開'),
  ('cmn-Hant-TW', 'cmn', 'components.expandBranch', '展開子分支'),
  ('cmn-Hant-TW', 'cmn', 'components.expandToolbar', '展開圖譜工具列'),
  ('cmn-Hant-TW', 'cmn', 'components.expression', '詞句')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'components.filterLanguages', '篩選語言…'),
  ('cmn-Hant-TW', 'cmn', 'components.fullscreen', '全螢幕'),
  ('cmn-Hant-TW', 'cmn', 'components.graphLabel', '詞句對應圖譜'),
  ('cmn-Hant-TW', 'cmn', 'components.graphLoading', '載入圖譜…'),
  ('cmn-Hant-TW', 'cmn', 'components.graphMode', '圖譜模式')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'components.graphStats', '{nodes} 個對應節點 · {edges} 個關係'),
  ('cmn-Hant-TW', 'cmn', 'components.graphToolbar', '圖譜工具列'),
  ('cmn-Hant-TW', 'cmn', 'components.hierarchyList', '對應階層列表'),
  ('cmn-Hant-TW', 'cmn', 'components.hops', '跳數'),
  ('cmn-Hant-TW', 'cmn', 'components.hoursAgo', '{count} 小時前')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'components.justNow', '剛剛'),
  ('cmn-Hant-TW', 'cmn', 'components.languageLoadFailed', '無法載入語言'),
  ('cmn-Hant-TW', 'cmn', 'components.listMode', '列表模式'),
  ('cmn-Hant-TW', 'cmn', 'components.loadMore', '載入更多'),
  ('cmn-Hant-TW', 'cmn', 'components.loadingRelated', '載入相關詞句中')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'components.locale', '語言環境'),
  ('cmn-Hant-TW', 'cmn', 'components.mapping', '對應'),
  ('cmn-Hant-TW', 'cmn', 'components.mappingScore', '對應評分'),
  ('cmn-Hant-TW', 'cmn', 'components.minutesAgo', '{count} 分鐘前'),
  ('cmn-Hant-TW', 'cmn', 'components.moreActions', '更多操作')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'components.moreMappings', '完整圖譜中還有 {count} 個對應'),
  ('cmn-Hant-TW', 'cmn', 'components.noDirectMappings', '尚無直接對應'),
  ('cmn-Hant-TW', 'cmn', 'components.noExpressions', '找不到相符詞句'),
  ('cmn-Hant-TW', 'cmn', 'components.nodeCount', '{count} 個節點'),
  ('cmn-Hant-TW', 'cmn', 'components.nodeInfo', '節點資訊')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'components.otherRelations', '其他關係'),
  ('cmn-Hant-TW', 'cmn', 'components.reading', '讀音'),
  ('cmn-Hant-TW', 'cmn', 'components.relatedExpressions', '相關詞句'),
  ('cmn-Hant-TW', 'cmn', 'components.relationCount', '{count} 個關係'),
  ('cmn-Hant-TW', 'cmn', 'components.removeLanguage', '移除 {code}')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'components.resetLayout', '重設版面配置'),
  ('cmn-Hant-TW', 'cmn', 'components.rootNode', '根節點'),
  ('cmn-Hant-TW', 'cmn', 'components.search', '搜尋'),
  ('cmn-Hant-TW', 'cmn', 'components.searchExpressions', '搜尋詞句…'),
  ('cmn-Hant-TW', 'cmn', 'components.searching', '搜尋中…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'components.selectNodeHint', '在圖譜中選取節點以檢視詳情'),
  ('cmn-Hant-TW', 'cmn', 'components.sourcePath', '來源路徑'),
  ('cmn-Hant-TW', 'cmn', 'components.upvote', '讚'),
  ('cmn-Hant-TW', 'cmn', 'components.viewExpression', '檢視詞句詳情'),
  ('cmn-Hant-TW', 'cmn', 'components.voteFailed', '投票失敗，已復原')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'components.zoomIn', '放大'),
  ('cmn-Hant-TW', 'cmn', 'components.zoomOut', '縮小'),
  ('cmn-Hant-TW', 'cmn', 'contribute.addExpression', '+ 新增詞句'),
  ('cmn-Hant-TW', 'cmn', 'contribute.chooseImage', '選擇圖片（最大 480px／100KB）'),
  ('cmn-Hant-TW', 'cmn', 'contribute.completeGraph', '完全圖')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'contribute.delete', '刪除'),
  ('cmn-Hant-TW', 'cmn', 'contribute.directMappingCount', '{count} 個直接對應'),
  ('cmn-Hant-TW', 'cmn', 'contribute.expression', '詞句'),
  ('cmn-Hant-TW', 'cmn', 'contribute.expressionCount', '{count} 個詞句'),
  ('cmn-Hant-TW', 'cmn', 'contribute.expressionPlaceholder', '輸入詞句…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'contribute.imageTooLarge', '壓縮後的圖片不得超過 100KB'),
  ('cmn-Hant-TW', 'cmn', 'contribute.imageUploadFailed', '無法上傳圖片'),
  ('cmn-Hant-TW', 'cmn', 'contribute.imageUploading', '上傳中…'),
  ('cmn-Hant-TW', 'cmn', 'contribute.language', '語言'),
  ('cmn-Hant-TW', 'cmn', 'contribute.lead', '提交意義相同的詞句。系統會在每對之間建立直接對應。複數、過去式、敬體等詞形變化請到詞句對應頁，不要在這裡提交。')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'contribute.locale', '語言環境'),
  ('cmn-Hant-TW', 'cmn', 'contribute.minRows', '至少需要 2 行，每行需填寫語言和詞句'),
  ('cmn-Hant-TW', 'cmn', 'contribute.submit', '提交'),
  ('cmn-Hant-TW', 'cmn', 'contribute.submitFailed', '提交失敗'),
  ('cmn-Hant-TW', 'cmn', 'contribute.submitting', '提交中…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'contribute.tags', '標籤'),
  ('cmn-Hant-TW', 'cmn', 'contribute.title', '批次提交'),
  ('cmn-Hant-TW', 'cmn', 'errors.home', '回首頁'),
  ('cmn-Hant-TW', 'cmn', 'errors.loadFailed', '無法載入'),
  ('cmn-Hant-TW', 'cmn', 'errors.pageMissing', '找不到頁面')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'expression.imageAlt', '詞句圖片'),
  ('cmn-Hant-TW', 'cmn', 'feed.all', '全部'),
  ('cmn-Hant-TW', 'cmn', 'feed.contributeMapping', '提交對應 →'),
  ('cmn-Hant-TW', 'cmn', 'feed.hot', '熱門'),
  ('cmn-Hant-TW', 'cmn', 'feed.mappingsAndExpressions', '對應 + 新詞句')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'feed.missing', '找不到所需內容？'),
  ('cmn-Hant-TW', 'cmn', 'feed.newContributions', '新貢獻'),
  ('cmn-Hant-TW', 'cmn', 'feed.newest', '最新'),
  ('cmn-Hant-TW', 'cmn', 'feed.noActivity', '暫無動態'),
  ('cmn-Hant-TW', 'cmn', 'feed.popularMappings', '熱門對應')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'feed.ratedThisWeek', '依評分 · 本週'),
  ('cmn-Hant-TW', 'cmn', 'feed.subtitle', '語意圖的最新脈動——熱門對應與新貢獻。'),
  ('cmn-Hant-TW', 'cmn', 'feed.title', '動態'),
  ('cmn-Hant-TW', 'cmn', 'handbook.addExpression', '新增詞句'),
  ('cmn-Hant-TW', 'cmn', 'handbook.addSection', '新增章節')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'handbook.back', '手冊列表'),
  ('cmn-Hant-TW', 'cmn', 'handbook.chapter', '第 {number} 章'),
  ('cmn-Hant-TW', 'cmn', 'handbook.closeExpressionInfo', '關閉詞句資訊'),
  ('cmn-Hant-TW', 'cmn', 'handbook.collapsePicker', '收合'),
  ('cmn-Hant-TW', 'cmn', 'handbook.deleteSection', '刪除章節')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'handbook.edit', '編輯手冊'),
  ('cmn-Hant-TW', 'cmn', 'handbook.expressionInfo', '詞句資訊'),
  ('cmn-Hant-TW', 'cmn', 'handbook.expressionInfoHint', '詞句的語言、地區和來源將顯示在此處。'),
  ('cmn-Hant-TW', 'cmn', 'handbook.helpful', '這本手冊有幫助嗎？'),
  ('cmn-Hant-TW', 'cmn', 'handbook.inspectorFailed', '無法載入詞句')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'handbook.loadFailed', '無法載入'),
  ('cmn-Hant-TW', 'cmn', 'handbook.locale', '語言'),
  ('cmn-Hant-TW', 'cmn', 'handbook.moveDown', '下移'),
  ('cmn-Hant-TW', 'cmn', 'handbook.moveSectionDown', '下移章節'),
  ('cmn-Hant-TW', 'cmn', 'handbook.moveSectionUp', '上移章節')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'handbook.moveUp', '上移'),
  ('cmn-Hant-TW', 'cmn', 'handbook.private', '私密'),
  ('cmn-Hant-TW', 'cmn', 'handbook.public', '公開'),
  ('cmn-Hant-TW', 'cmn', 'handbook.publish', '發布'),
  ('cmn-Hant-TW', 'cmn', 'handbook.region', '地區')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'handbook.relationsFailed', '無法載入相關詞句'),
  ('cmn-Hant-TW', 'cmn', 'handbook.removeExpression', '移除 {text}'),
  ('cmn-Hant-TW', 'cmn', 'handbook.saveDraft', '儲存草稿'),
  ('cmn-Hant-TW', 'cmn', 'handbook.saving', '儲存中…'),
  ('cmn-Hant-TW', 'cmn', 'handbook.sectionTitle', '章節標題')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'handbook.selectExpression', '選擇詞句'),
  ('cmn-Hant-TW', 'cmn', 'handbook.source', '來源'),
  ('cmn-Hant-TW', 'cmn', 'handbook.sourceAi', 'AI'),
  ('cmn-Hant-TW', 'cmn', 'handbook.sourceAuthority', '權威'),
  ('cmn-Hant-TW', 'cmn', 'handbook.sourceUser', '使用者')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'handbook.titlePlaceholder', '手冊標題'),
  ('cmn-Hant-TW', 'cmn', 'handbook.toc', '目錄'),
  ('cmn-Hant-TW', 'cmn', 'handbook.viewFullGraph', '檢視完整關係圖'),
  ('cmn-Hant-TW', 'cmn', 'handbook.visibility', '可見性'),
  ('cmn-Hant-TW', 'cmn', 'handbooks.create', '新增手冊')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'handbooks.loadFailed', '無法載入手冊'),
  ('cmn-Hant-TW', 'cmn', 'handbooks.newest', '最新'),
  ('cmn-Hant-TW', 'cmn', 'handbooks.noResults', '找不到手冊'),
  ('cmn-Hant-TW', 'cmn', 'handbooks.popular', '熱門'),
  ('cmn-Hant-TW', 'cmn', 'handbooks.searchPlaceholder', '搜尋手冊…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'handbooks.sections', '章節'),
  ('cmn-Hant-TW', 'cmn', 'handbooks.title', '手冊'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.back', '上一步'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.cancel', '取消'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.close', '關閉')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'languageCreate.create', '建立語言'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.createFailed', '語言建立失敗'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.creating', '建立中…'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.errorDescription', '請輸入描述'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.errorGlottolog', '請選擇 Glottolog 比對或選擇「無比對」')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'languageCreate.errorName', '請輸入語言名稱'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.errorReason', '請選擇僅限社群建立的原因'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.errorTag', '請輸入語言子標籤以繼續'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.glottologCandidates', '找到 {count} 個候選'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.glottologChoose', '選擇比對或標示無合適條目')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'languageCreate.glottologExactMatch', '比對此候選'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.glottologLevelDialect', '方言'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.glottologLevelLanguage', '語言'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.glottologNoMatch', 'Glottolog 無合適條目'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.glottologSearchPlaceholder', '搜尋 Glottolog…')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('cmn-Hant-TW', 'cmn', 'languageCreate.metadataDescription', '描述'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.metadataDescriptionPlaceholder', '描述此語言或變體…'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.metadataName', '名稱'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.metadataNameEn', '英文名稱'),
  ('cmn-Hant-TW', 'cmn', 'languageCreate.metadataReason', '為何此語言未收錄於 Glottolog？')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
-- Done