-- AUTO-GENERATED by scripts/i18n/generate-bundle.py. Do not edit.
-- Project: langmap-web; direct UI translation semantic edges.
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.collapseToFirst', 'Colapsar al primer nivel'),
  ('spa-Latn-ES', 'spa', 'components.daysAgo', 'Hace {count} días'),
  ('spa-Latn-ES', 'spa', 'components.depth', 'Profundidad {depth}'),
  ('spa-Latn-ES', 'spa', 'components.directMappingList', 'Expresiones con relación directa'),
  ('spa-Latn-ES', 'spa', 'components.downvote', 'Votar en contra')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.edgeCount', '{count} aristas'),
  ('spa-Latn-ES', 'spa', 'components.empty', 'Aún no hay datos'),
  ('spa-Latn-ES', 'spa', 'components.evidence', 'Evidencia'),
  ('spa-Latn-ES', 'spa', 'components.exitFullscreen', 'Salir de pantalla completa'),
  ('spa-Latn-ES', 'spa', 'components.expand', 'Expandir')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.expandAll', 'Expandir todo'),
  ('spa-Latn-ES', 'spa', 'components.expandBranch', 'Expandir rama hija'),
  ('spa-Latn-ES', 'spa', 'components.expression', 'Expresión'),
  ('spa-Latn-ES', 'spa', 'components.filterLanguages', 'Filtrar idiomas…'),
  ('spa-Latn-ES', 'spa', 'components.fullscreen', 'Pantalla completa')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.graphLabel', 'Grafo de relaciones de expresiones'),
  ('spa-Latn-ES', 'spa', 'components.graphLoading', 'Cargando grafo…'),
  ('spa-Latn-ES', 'spa', 'components.graphMode', 'Modo grafo'),
  ('spa-Latn-ES', 'spa', 'components.graphStats', '{nodes} nodos mapeados · {edges} relaciones'),
  ('spa-Latn-ES', 'spa', 'components.graphToolbar', 'Barra de herramientas del grafo')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.hierarchyList', 'Lista jerárquica de relaciones'),
  ('spa-Latn-ES', 'spa', 'components.hops', 'Saltos'),
  ('spa-Latn-ES', 'spa', 'components.hoursAgo', 'Hace {count} horas'),
  ('spa-Latn-ES', 'spa', 'components.justNow', 'Ahora mismo'),
  ('spa-Latn-ES', 'spa', 'components.languageLoadFailed', 'No se pudieron cargar los idiomas')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.listMode', 'Modo lista'),
  ('spa-Latn-ES', 'spa', 'components.loadMore', 'Cargar más'),
  ('spa-Latn-ES', 'spa', 'components.loadingRelated', 'Cargando expresiones relacionadas'),
  ('spa-Latn-ES', 'spa', 'components.locale', 'Entorno lingüístico'),
  ('spa-Latn-ES', 'spa', 'components.mapping', 'Relación')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.mappingScore', 'Puntuación de la relación'),
  ('spa-Latn-ES', 'spa', 'components.minutesAgo', 'Hace {count} minutos'),
  ('spa-Latn-ES', 'spa', 'components.moreActions', 'Más acciones'),
  ('spa-Latn-ES', 'spa', 'components.moreMappings', '{count} relaciones más disponibles en el grafo completo'),
  ('spa-Latn-ES', 'spa', 'components.noDirectMappings', 'Aún no hay relaciones directas')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.noExpressions', 'No se encontraron expresiones'),
  ('spa-Latn-ES', 'spa', 'components.nodeCount', '{count} nodos'),
  ('spa-Latn-ES', 'spa', 'components.nodeInfo', 'Información del nodo'),
  ('spa-Latn-ES', 'spa', 'components.otherRelations', 'Otras relaciones'),
  ('spa-Latn-ES', 'spa', 'components.reading', 'Lectura')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.relatedExpressions', 'Expresiones relacionadas'),
  ('spa-Latn-ES', 'spa', 'components.relationCount', '{count} relaciones'),
  ('spa-Latn-ES', 'spa', 'components.removeLanguage', 'Eliminar {code}'),
  ('spa-Latn-ES', 'spa', 'components.resetLayout', 'Restablecer diseño'),
  ('spa-Latn-ES', 'spa', 'components.rootNode', 'Nodo raíz')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.search', 'Buscar'),
  ('spa-Latn-ES', 'spa', 'components.searchExpressions', 'Buscar expresiones…'),
  ('spa-Latn-ES', 'spa', 'components.searching', 'Buscando…'),
  ('spa-Latn-ES', 'spa', 'components.selectNodeHint', 'Selecciona un nodo en el grafo para ver detalles'),
  ('spa-Latn-ES', 'spa', 'components.sourcePath', 'Ruta de origen')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'components.upvote', 'Votar a favor'),
  ('spa-Latn-ES', 'spa', 'components.viewExpression', 'Ver detalles de la expresión'),
  ('spa-Latn-ES', 'spa', 'components.voteFailed', 'Voto fallido; revertido'),
  ('spa-Latn-ES', 'spa', 'components.zoomIn', 'Acercar'),
  ('spa-Latn-ES', 'spa', 'components.zoomOut', 'Alejar')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'contribute.addExpression', '+ Añadir expresión'),
  ('spa-Latn-ES', 'spa', 'contribute.completeGraph', 'Grafo completo'),
  ('spa-Latn-ES', 'spa', 'contribute.delete', 'Eliminar'),
  ('spa-Latn-ES', 'spa', 'contribute.directMappingCount', '{count} relaciones directas'),
  ('spa-Latn-ES', 'spa', 'contribute.expression', 'Expresión')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'contribute.expressionCount', '{count} expresiones'),
  ('spa-Latn-ES', 'spa', 'contribute.expressionPlaceholder', 'Introduce una expresión…'),
  ('spa-Latn-ES', 'spa', 'contribute.language', 'Idioma'),
  ('spa-Latn-ES', 'spa', 'contribute.lead', 'Envía expresiones que significan lo mismo. El sistema crea una relación directa entre cada par. Las formas flexionadas (plural, pasado, cortesía) se añaden en la página de correspondencias, no aquí.'),
  ('spa-Latn-ES', 'spa', 'contribute.locale', 'Idioma')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'contribute.minRows', 'Se requieren al menos 2 filas con idioma y expresión'),
  ('spa-Latn-ES', 'spa', 'contribute.submit', 'Enviar'),
  ('spa-Latn-ES', 'spa', 'contribute.submitFailed', 'Error al enviar'),
  ('spa-Latn-ES', 'spa', 'contribute.submitting', 'Enviando…'),
  ('spa-Latn-ES', 'spa', 'contribute.tags', 'Etiquetas')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'contribute.title', 'Contribución por lotes'),
  ('spa-Latn-ES', 'spa', 'errors.home', 'Volver al inicio'),
  ('spa-Latn-ES', 'spa', 'errors.loadFailed', 'No se pudo cargar'),
  ('spa-Latn-ES', 'spa', 'errors.pageMissing', 'Página no encontrada'),
  ('spa-Latn-ES', 'spa', 'expression.imageAlt', 'Imagen de la expresión')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'feed.all', 'Todo'),
  ('spa-Latn-ES', 'spa', 'feed.contributeMapping', 'Contribuir una relación →'),
  ('spa-Latn-ES', 'spa', 'feed.hot', 'Popular'),
  ('spa-Latn-ES', 'spa', 'feed.mappingsAndExpressions', 'Relaciones + nuevas expresiones'),
  ('spa-Latn-ES', 'spa', 'feed.missing', '¿No encuentras lo que buscas?')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'feed.newContributions', 'Nuevas contribuciones'),
  ('spa-Latn-ES', 'spa', 'feed.newest', 'Más reciente'),
  ('spa-Latn-ES', 'spa', 'feed.noActivity', 'No hay actividad'),
  ('spa-Latn-ES', 'spa', 'feed.popularMappings', 'Relaciones populares'),
  ('spa-Latn-ES', 'spa', 'feed.ratedThisWeek', 'Por puntuación · esta semana')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'feed.subtitle', 'El pulso más reciente del grafo semántico: relaciones populares y nuevas contribuciones.'),
  ('spa-Latn-ES', 'spa', 'feed.title', 'Actividad'),
  ('spa-Latn-ES', 'spa', 'handbook.addExpression', 'Añadir expresión'),
  ('spa-Latn-ES', 'spa', 'handbook.addSection', 'Añadir sección'),
  ('spa-Latn-ES', 'spa', 'handbook.back', 'Lista de manuales')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbook.chapter', 'Capítulo {number}'),
  ('spa-Latn-ES', 'spa', 'handbook.closeExpressionInfo', 'Cerrar información de la expresión'),
  ('spa-Latn-ES', 'spa', 'handbook.collapsePicker', 'Colapsar'),
  ('spa-Latn-ES', 'spa', 'handbook.deleteSection', 'Eliminar sección'),
  ('spa-Latn-ES', 'spa', 'handbook.edit', 'Editar manual')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbook.expressionInfo', 'Información de la expresión'),
  ('spa-Latn-ES', 'spa', 'handbook.expressionInfoHint', 'El idioma, la región y la fuente de la expresión aparecerán aquí.'),
  ('spa-Latn-ES', 'spa', 'handbook.helpful', '¿Te resultó útil este manual?'),
  ('spa-Latn-ES', 'spa', 'handbook.inspectorFailed', 'No se pudo cargar la expresión'),
  ('spa-Latn-ES', 'spa', 'handbook.loadFailed', 'No se pudo cargar')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbook.locale', 'Idioma'),
  ('spa-Latn-ES', 'spa', 'handbook.moveDown', 'Mover abajo'),
  ('spa-Latn-ES', 'spa', 'handbook.moveSectionDown', 'Mover sección abajo'),
  ('spa-Latn-ES', 'spa', 'handbook.moveSectionUp', 'Mover sección arriba'),
  ('spa-Latn-ES', 'spa', 'handbook.moveUp', 'Mover arriba')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbook.private', 'Privado'),
  ('spa-Latn-ES', 'spa', 'handbook.public', 'Público'),
  ('spa-Latn-ES', 'spa', 'handbook.publish', 'Publicar'),
  ('spa-Latn-ES', 'spa', 'handbook.region', 'Región'),
  ('spa-Latn-ES', 'spa', 'handbook.relationsFailed', 'No se pudieron cargar las expresiones relacionadas')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbook.removeExpression', 'Eliminar {text}'),
  ('spa-Latn-ES', 'spa', 'handbook.saveDraft', 'Guardar borrador'),
  ('spa-Latn-ES', 'spa', 'handbook.saving', 'Guardando…'),
  ('spa-Latn-ES', 'spa', 'handbook.sectionTitle', 'Título de la sección'),
  ('spa-Latn-ES', 'spa', 'handbook.selectExpression', 'Seleccionar una expresión')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbook.source', 'Fuente'),
  ('spa-Latn-ES', 'spa', 'handbook.sourceAi', 'IA'),
  ('spa-Latn-ES', 'spa', 'handbook.sourceAuthority', 'Autoridad'),
  ('spa-Latn-ES', 'spa', 'handbook.sourceUser', 'Usuario'),
  ('spa-Latn-ES', 'spa', 'handbook.titlePlaceholder', 'Título del manual')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbook.toc', 'Contenido'),
  ('spa-Latn-ES', 'spa', 'handbook.viewFullGraph', 'Ver grafo completo de relaciones'),
  ('spa-Latn-ES', 'spa', 'handbook.visibility', 'Visibilidad'),
  ('spa-Latn-ES', 'spa', 'handbooks.create', 'Nuevo manual'),
  ('spa-Latn-ES', 'spa', 'handbooks.loadFailed', 'No se pudieron cargar los manuales')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbooks.newest', 'Más reciente'),
  ('spa-Latn-ES', 'spa', 'handbooks.noResults', 'No se encontraron manuales'),
  ('spa-Latn-ES', 'spa', 'handbooks.popular', 'Popular'),
  ('spa-Latn-ES', 'spa', 'handbooks.searchPlaceholder', 'Buscar manuales…'),
  ('spa-Latn-ES', 'spa', 'handbooks.sections', 'secciones')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'handbooks.title', 'Manuales'),
  ('spa-Latn-ES', 'spa', 'languageCreate.back', 'Atrás'),
  ('spa-Latn-ES', 'spa', 'languageCreate.cancel', 'Cancelar'),
  ('spa-Latn-ES', 'spa', 'languageCreate.close', 'Cerrar'),
  ('spa-Latn-ES', 'spa', 'languageCreate.create', 'Crear idioma')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.createFailed', 'Error al crear el idioma'),
  ('spa-Latn-ES', 'spa', 'languageCreate.creating', 'Creando…'),
  ('spa-Latn-ES', 'spa', 'languageCreate.errorDescription', 'Introduce una descripción'),
  ('spa-Latn-ES', 'spa', 'languageCreate.errorGlottolog', 'Elige una coincidencia Glottolog o selecciona «sin coincidencia»'),
  ('spa-Latn-ES', 'spa', 'languageCreate.errorName', 'Introduce un nombre de idioma')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.errorReason', 'Selecciona un motivo para la creación solo comunitaria'),
  ('spa-Latn-ES', 'spa', 'languageCreate.errorTag', 'Introduce una subetiqueta de idioma para continuar'),
  ('spa-Latn-ES', 'spa', 'languageCreate.glottologCandidates', '{count} candidato(s) encontrado(s)'),
  ('spa-Latn-ES', 'spa', 'languageCreate.glottologChoose', 'Elige una coincidencia o indica que no hay entrada adecuada'),
  ('spa-Latn-ES', 'spa', 'languageCreate.glottologExactMatch', 'Elegir este candidato')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.glottologLevelDialect', 'dialecto'),
  ('spa-Latn-ES', 'spa', 'languageCreate.glottologLevelLanguage', 'idioma'),
  ('spa-Latn-ES', 'spa', 'languageCreate.glottologNoMatch', 'Glottolog no tiene una entrada adecuada'),
  ('spa-Latn-ES', 'spa', 'languageCreate.glottologSearchPlaceholder', 'Buscar en Glottolog…'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataDescription', 'Descripción')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataDescriptionPlaceholder', 'Describe este idioma o variedad…'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataName', 'Nombre'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataNameEn', 'Nombre en inglés'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataReason', '¿Por qué falta este idioma en Glottolog?'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataReasonCommunity', 'Uso específico de la comunidad')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataReasonEmerging', 'Variante emergente'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataReasonMissing', 'Falta en Glottolog'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataReasonOther', 'Otro'),
  ('spa-Latn-ES', 'spa', 'languageCreate.metadataReasonPlaceholder', 'Selecciona un motivo…'),
  ('spa-Latn-ES', 'spa', 'languageCreate.next', 'Siguiente')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.optional', 'Opcional'),
  ('spa-Latn-ES', 'spa', 'languageCreate.previewCanonicalCode', 'Código canónico'),
  ('spa-Latn-ES', 'spa', 'languageCreate.previewExisting', 'Este idioma ya existe'),
  ('spa-Latn-ES', 'spa', 'languageCreate.previewExistingAction', 'Usar idioma existente'),
  ('spa-Latn-ES', 'spa', 'languageCreate.previewTitle', 'Crear idioma')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.previewWarnings', 'Advertencias'),
  ('spa-Latn-ES', 'spa', 'languageCreate.provisionalTag', 'Etiqueta provisional'),
  ('spa-Latn-ES', 'spa', 'languageCreate.requiredHint', 'Los campos con * son obligatorios'),
  ('spa-Latn-ES', 'spa', 'languageCreate.stepGlottolog', 'Coincidencia Glottolog'),
  ('spa-Latn-ES', 'spa', 'languageCreate.stepMetadata', 'Metadatos')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.stepPreview', 'Vista previa y crear'),
  ('spa-Latn-ES', 'spa', 'languageCreate.stepTag', 'Etiqueta de idioma'),
  ('spa-Latn-ES', 'spa', 'languageCreate.subtagLanguage', 'Idioma'),
  ('spa-Latn-ES', 'spa', 'languageCreate.subtagRegion', 'Región'),
  ('spa-Latn-ES', 'spa', 'languageCreate.subtagScript', 'Escritura')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageCreate.subtagSearch', 'Buscar subetiquetas…'),
  ('spa-Latn-ES', 'spa', 'languageCreate.subtagVariant', 'Variante'),
  ('spa-Latn-ES', 'spa', 'languageCreate.variantRemoved', '1 variante eliminada'),
  ('spa-Latn-ES', 'spa', 'languageCreate.variantsRemoved', '{count} variante(s) eliminada(s)'),
  ('spa-Latn-ES', 'spa', 'languageDetail.allOthers', 'Todos')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageDetail.allVariants', 'Todas las variantes'),
  ('spa-Latn-ES', 'spa', 'languageDetail.alphabetical', 'Alfabético'),
  ('spa-Latn-ES', 'spa', 'languageDetail.back', 'Idiomas'),
  ('spa-Latn-ES', 'spa', 'languageDetail.expressions', 'Expresiones'),
  ('spa-Latn-ES', 'spa', 'languageDetail.latest', 'Más reciente')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageDetail.loadFailed', 'No se pudo cargar'),
  ('spa-Latn-ES', 'spa', 'languageDetail.mapped', 'Mapeado'),
  ('spa-Latn-ES', 'spa', 'languageDetail.noResults', 'No se encontraron expresiones'),
  ('spa-Latn-ES', 'spa', 'languageDetail.otherLabel', 'Otro'),
  ('spa-Latn-ES', 'spa', 'languageDetail.popular', 'Popular')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageDetail.regionalForms', 'Formas regionales'),
  ('spa-Latn-ES', 'spa', 'languageDetail.representativeCities', 'Ciudades representativas'),
  ('spa-Latn-ES', 'spa', 'languageDetail.representativeCitiesNote', 'Estas ciudades son solo orientativas'),
  ('spa-Latn-ES', 'spa', 'languageDetail.scripts.Hans', 'Chino simplificado'),
  ('spa-Latn-ES', 'spa', 'languageDetail.scripts.Hant', 'Chino tradicional')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageDetail.scripts.Jpan', 'Japonés'),
  ('spa-Latn-ES', 'spa', 'languageDetail.scripts.Latn', 'Latino'),
  ('spa-Latn-ES', 'spa', 'languageDetail.searchPlaceholder', 'Buscar expresiones…'),
  ('spa-Latn-ES', 'spa', 'languageDetail.variantLabel', 'Escritura'),
  ('spa-Latn-ES', 'spa', 'languagePicker.clear', 'Limpiar selección')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languagePicker.createLanguage', 'Crear nuevo idioma o variedad'),
  ('spa-Latn-ES', 'spa', 'languagePicker.noResults', 'No hay idiomas coincidentes'),
  ('spa-Latn-ES', 'spa', 'languagePicker.placeholder', 'Buscar idiomas…'),
  ('spa-Latn-ES', 'spa', 'languageSwitcher.browserSuggested', 'Sugerido por tu navegador'),
  ('spa-Latn-ES', 'spa', 'languageSwitcher.helpTranslate', 'Ayuda a traducir LangMap')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languageSwitcher.noResults', 'No hay idiomas coincidentes'),
  ('spa-Latn-ES', 'spa', 'languageSwitcher.recent', 'Idiomas recientes'),
  ('spa-Latn-ES', 'spa', 'languagesPage.addLanguage', 'Añadir idioma'),
  ('spa-Latn-ES', 'spa', 'languagesPage.expressionCount', 'Expresiones'),
  ('spa-Latn-ES', 'spa', 'languagesPage.languageCount', 'Idiomas')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languagesPage.loadFailed', 'No se pudieron cargar los idiomas'),
  ('spa-Latn-ES', 'spa', 'languagesPage.noResults', 'No se encontraron idiomas'),
  ('spa-Latn-ES', 'spa', 'languagesPage.searchPlaceholder', 'Buscar idiomas…'),
  ('spa-Latn-ES', 'spa', 'languagesPage.sortAlphabetical', 'A–Z'),
  ('spa-Latn-ES', 'spa', 'languagesPage.sortCount', 'Cantidad')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'languagesPage.subtitle', 'Explorar expresiones y relaciones entre todos los idiomas'),
  ('spa-Latn-ES', 'spa', 'languagesPage.title', 'Idiomas'),
  ('spa-Latn-ES', 'spa', 'localeCreate.codePreviewEmpty', 'Completa los campos obligatorios para previsualizar el código'),
  ('spa-Latn-ES', 'spa', 'localeCreate.create', 'Crear locale'),
  ('spa-Latn-ES', 'spa', 'localeCreate.createFailed', 'Error al crear el locale')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'localeCreate.englishName', 'Nombre en inglés'),
  ('spa-Latn-ES', 'spa', 'localeCreate.heading', 'Crear locale de idioma'),
  ('spa-Latn-ES', 'spa', 'localeCreate.latitude', 'Latitud'),
  ('spa-Latn-ES', 'spa', 'localeCreate.localName', 'Nombre local'),
  ('spa-Latn-ES', 'spa', 'localeCreate.longitude', 'Longitud')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'localeCreate.place', 'Segmentos de lugar'),
  ('spa-Latn-ES', 'spa', 'localeCreate.placePlaceholder', 'Quanzhou_Nanan'),
  ('spa-Latn-ES', 'spa', 'localeCreate.region', 'Región'),
  ('spa-Latn-ES', 'spa', 'localeCreate.regionPlaceholder', 'Código ISO 3166-1'),
  ('spa-Latn-ES', 'spa', 'localeCreate.script', 'Escritura')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'localeCreate.scriptPlaceholder', 'Código ISO 15924'),
  ('spa-Latn-ES', 'spa', 'mapLens.anchor', 'Ancla'),
  ('spa-Latn-ES', 'spa', 'mapLens.back', 'Volver a la relación'),
  ('spa-Latn-ES', 'spa', 'mapLens.languages', '{count} idiomas'),
  ('spa-Latn-ES', 'spa', 'mapLens.loadFailed', 'No se pudo cargar')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mapLens.members', 'Miembros de la relación'),
  ('spa-Latn-ES', 'spa', 'mapLens.noData', 'No hay datos de distribución geográfica para esta expresión'),
  ('spa-Latn-ES', 'spa', 'mapLens.regions', '{count} regiones'),
  ('spa-Latn-ES', 'spa', 'mapLens.title', 'Distribución de la expresión'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.addAndMap', 'Añadir y crear relación')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mappingDetail.addExpression', 'Añadir expresión'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.addFailed', 'No se pudo añadir la expresión'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.adding', 'Añadiendo…'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.authority', 'Autoridad'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.breadcrumb', 'Ruta de navegación')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mappingDetail.closeQuickAdd', 'Cerrar adición rápida'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.contribute', 'Contribuir relación'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.direct', 'relaciones directas'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.enterRequired', 'Introduce expresión y código de idioma'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.expression', 'Expresión')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mappingDetail.expressionPlaceholder', 'Introduce una expresión…'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.graph', 'Grafo'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.home', 'Inicio'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.hops', 'saltos'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.indirect', 'indirecta')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mappingDetail.languageCode', 'Código de idioma'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.languageCodePlaceholder', 'ej. en / cmn-Hant'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.list', 'Lista'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.loadFailed', 'No se pudo cargar'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.mappingSet', 'Conjunto de relaciones')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mappingDetail.noMappings', 'Aún no hay relaciones'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.optional', 'Opcional'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.quickAdd', 'Añadir expresión rápidamente'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.quickAddLead', 'Añade una expresión y relaciónala directamente con la expresión actual.'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.region', 'Región')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'mappingDetail.user', 'Usuario'),
  ('spa-Latn-ES', 'spa', 'mappingDetail.viewMap', 'Ver esta expresión en el mapa'),
  ('spa-Latn-ES', 'spa', 'morphology.addFormLink', 'Añadir enlace de forma'),
  ('spa-Latn-ES', 'spa', 'morphology.class.adjective', 'Adjetivo'),
  ('spa-Latn-ES', 'spa', 'morphology.class.noun', 'Sustantivo')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'morphology.class.verb', 'Verbo'),
  ('spa-Latn-ES', 'spa', 'morphology.dictionaryForm', 'Forma de diccionario'),
  ('spa-Latn-ES', 'spa', 'morphology.empty', 'Aún no hay enlaces de forma'),
  ('spa-Latn-ES', 'spa', 'morphology.formOfAria', 'Forma de {lemma}: {features}'),
  ('spa-Latn-ES', 'spa', 'morphology.hideForm', 'Ocultar formulario')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'morphology.loadFailed', 'No se pudieron cargar las formas'),
  ('spa-Latn-ES', 'spa', 'morphology.markAsForm', 'Marcar como forma de…'),
  ('spa-Latn-ES', 'spa', 'morphology.noLanguageFeatures', 'No hay rasgos habituales para esta clase. Puedes guardar el enlace o mostrar todos los rasgos.'),
  ('spa-Latn-ES', 'spa', 'morphology.pickFeatures', 'Rasgos'),
  ('spa-Latn-ES', 'spa', 'morphology.pickFeaturesHint', 'Opcional. Solo se muestran los rasgos habituales de este idioma y esta clase.')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'morphology.saved', 'Enlace de forma guardado'),
  ('spa-Latn-ES', 'spa', 'morphology.saving', 'Guardando…'),
  ('spa-Latn-ES', 'spa', 'morphology.searchLemma', 'Buscar una forma de diccionario en el mismo idioma'),
  ('spa-Latn-ES', 'spa', 'morphology.searchLemmaLabel', 'Forma de diccionario'),
  ('spa-Latn-ES', 'spa', 'morphology.showAllFeatures', 'Mostrar todos los rasgos')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'morphology.submit', 'Guardar enlace de forma'),
  ('spa-Latn-ES', 'spa', 'morphology.submitFailed', 'No se pudo guardar el enlace de forma'),
  ('spa-Latn-ES', 'spa', 'morphology.title', 'Formas de la palabra'),
  ('spa-Latn-ES', 'spa', 'morphology.wordClass', 'Clase de palabra'),
  ('spa-Latn-ES', 'spa', 'morphology.wordClassHint', 'Elige primero sustantivo, verbo o adjetivo. Los rasgos dependen de eso.')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'nav.closeMenu', 'Cerrar menú'),
  ('spa-Latn-ES', 'spa', 'nav.contribute', 'Contribuir'),
  ('spa-Latn-ES', 'spa', 'nav.handbooks', 'Manuales'),
  ('spa-Latn-ES', 'spa', 'nav.home', 'Inicio'),
  ('spa-Latn-ES', 'spa', 'nav.languages', 'Idiomas')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
WITH ui_translation_seed(locale_code, lang_code, message_key, text) AS (VALUES
  ('spa-Latn-ES', 'spa', 'nav.menu', 'Menú'),
  ('spa-Latn-ES', 'spa', 'nav.openMenu', 'Abrir menú'),
  ('spa-Latn-ES', 'spa', 'nav.searchExpressions', 'Buscar expresiones'),
  ('spa-Latn-ES', 'spa', 'nav.signIn', 'Iniciar sesión'),
  ('spa-Latn-ES', 'spa', 'nav.signOut', 'Cerrar sesión')
) INSERT OR IGNORE INTO expression_edges(expression_a_id, expression_b_id, relation_mask) SELECT CASE WHEN m.source_expression_id < e.id THEN m.source_expression_id ELSE e.id END, CASE WHEN m.source_expression_id < e.id THEN e.id ELSE m.source_expression_id END, 1 FROM ui_translation_seed t JOIN ui_messages m ON m.project_id='langmap-web' AND m.message_key=t.message_key JOIN languages l ON l.code=t.lang_code JOIN expressions e ON e.language_id=l.id AND e.text=t.text AND e.homograph_index=1 WHERE m.source_expression_id<>e.id;
-- Done