#!/usr/bin/env python3
"""Generate seed SQL for UI messages from web/src/locales/en.ts.

Creates English Expressions (eng:{text_hash}) and ui_messages rows for the
langmap-web project. Output: artifacts/system-ui/system-ui.sql.

Each Expression gets source_id='system-ui', source_ref='ui:langmap-web:{key}:1'.
"""
from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
EN_TS_PATH = PROJECT_ROOT / "web" / "src" / "locales" / "en.ts"
OUTPUT_PATH = Path(__file__).resolve().parent / "artifacts" / "system-ui" / "system-ui.sql"
PROJECT_ID = "langmap-web"
LANG_CODE = "eng"


def _load_i18n_sql_module():
    module_path = Path(__file__).with_name("generate-i18n-sql.py")
    spec = importlib.util.spec_from_file_location("generate_i18n_sql", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"unable to load {module_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


i18n_sql = _load_i18n_sql_module()


# Identity helpers are shared with generate-i18n-sql.py so seeded source ids match
# runtime createExpression ids exactly (canonicalize + compute_text_hash + build).
compute_text_hash = i18n_sql.compute_text_hash
canonicalize_expression_text = i18n_sql.canonicalize_expression_text
build_expression_id = i18n_sql.build_expression_id
extract_placeholders = i18n_sql.extract_placeholders


def parse_en_ts(content: str) -> dict[str, str]:
    return i18n_sql.parse_en_ts_text(content)


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> int:
    content = EN_TS_PATH.read_text(encoding="utf-8")
    messages = parse_en_ts(content)
    if not messages:
        print("ERROR: no messages parsed from en.ts", file=sys.stderr)
        return 1

    lines = [
        "-- AUTO-GENERATED by scripts/i18n/generate-ui-seed.py. Do not edit.",
        f"-- {len(messages)} UI messages for project '{PROJECT_ID}'.",
        "",
    ]

    for key in sorted(messages):
        text = canonicalize_expression_text(messages[key])
        text_hash = compute_text_hash(text)
        expr_id = build_expression_id(LANG_CODE, text_hash)
        placeholders = json.dumps(extract_placeholders(text))

        lines.append(f"-- {key}")
        lines.append(
            f"INSERT OR IGNORE INTO expressions (id, lang_code, text, text_hash, homograph_index, "
            f"description, tags_json, source_id, source_ref, review_status, created_by) "
            f"VALUES ({sql_str(expr_id)}, {sql_str(LANG_CODE)}, {sql_str(text)}, {sql_str(text_hash)}, "
            f"1, '', '[]', 'system-ui', {sql_str(f'ui:{PROJECT_ID}:{key}:1')}, 'approved', NULL);"
        )
        lines.append(
            f"INSERT OR IGNORE INTO ui_messages (project_id, message_key, source_expression_id, "
            f"source_text, placeholders_json, status) "
            f"VALUES ({sql_str(PROJECT_ID)}, {sql_str(key)}, {sql_str(expr_id)}, {sql_str(text)}, "
            f"{sql_str(placeholders)}, 'active');"
        )
        lines.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT_PATH} ({len(messages)} messages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
