import { Hono } from 'hono';
import auth from './auth';
import languages from './languages';
import expressions from './expressions';
import mappings from './mappings';
import contributions from './contributions';
import handbooks from './handbooks';
import feed from './feed';
import search from './search';

const api = new Hono();
api.route('/auth', auth);
api.route('/languages', languages);
api.route('/expressions', expressions);
api.route('/mappings', mappings);
api.route('/contributions', contributions);
api.route('/handbooks', handbooks);
api.route('/feed', feed);
api.route('/search', search);
export default api;
