-- Canonical greenfield schema for PostgreSQL baseline.
-- The 0039 migration is intentionally destructive and has the same contract.


CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user',
  email_verified BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE languages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name_en TEXT NOT NULL,
  name_expression_id BIGINT
);

CREATE TABLE language_statistics (
  language_id BIGINT PRIMARY KEY,
  expression_count BIGINT NOT NULL DEFAULT 0,
  locale_count BIGINT NOT NULL DEFAULT 0,
  active_ui_locale_count BIGINT NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  FOREIGN KEY (language_id) REFERENCES languages(id) ON DELETE CASCADE
);

CREATE TABLE scripts (
  code TEXT PRIMARY KEY,
  name_en TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('ltr', 'rtl')),
  name_expression_id BIGINT
);

CREATE TABLE regions (
  code TEXT PRIMARY KEY,
  name_en TEXT NOT NULL,
  name_expression_id BIGINT,
  latitude REAL,
  longitude REAL,
  CHECK ((latitude IS NULL) = (longitude IS NULL))
);

CREATE TABLE language_locales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  language_id BIGINT NOT NULL,
  script_code TEXT,
  orthography TEXT,
  region_code TEXT,
  place_path TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL,
  name_en TEXT NOT NULL,
  name_expression_id BIGINT,
  latitude REAL,
  longitude REAL,
  CHECK ((latitude IS NULL) = (longitude IS NULL)),
  FOREIGN KEY (language_id) REFERENCES languages(id) ON DELETE RESTRICT,
  FOREIGN KEY (script_code) REFERENCES scripts(code) ON DELETE RESTRICT,
  FOREIGN KEY (region_code) REFERENCES regions(code) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX idx_language_locales_identity
  ON language_locales(language_id, COALESCE(script_code, ''), COALESCE(orthography, ''), COALESCE(region_code, ''), place_path);

CREATE TABLE sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  UNIQUE (type, name)
);

CREATE TABLE parts_of_speech (
  code TEXT PRIMARY KEY,
  name_en TEXT NOT NULL,
  sort_order BIGINT NOT NULL UNIQUE,
  bit_index BIGINT NOT NULL UNIQUE CHECK (bit_index BETWEEN 0 AND 62)
);

CREATE TABLE expressions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  language_id BIGINT NOT NULL,
  text TEXT NOT NULL,
  homograph_index BIGINT NOT NULL DEFAULT 1 CHECK (homograph_index >= 1),
  pos_mask BIGINT NOT NULL DEFAULT 0 CHECK (pos_mask >= 0),
  source_id BIGINT,
  created_by BIGINT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  UNIQUE (language_id, text, homograph_index),
  FOREIGN KEY (language_id) REFERENCES languages(id) ON DELETE RESTRICT,
  FOREIGN KEY (source_id) REFERENCES sources(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_expressions_language_created ON expressions(language_id, created_at DESC);

CREATE TABLE expression_locale_links (
  expression_id BIGINT NOT NULL,
  locale_id BIGINT NOT NULL,
  PRIMARY KEY (expression_id, locale_id),
  FOREIGN KEY (expression_id) REFERENCES expressions(id) ON DELETE CASCADE,
  FOREIGN KEY (locale_id) REFERENCES language_locales(id) ON DELETE RESTRICT
);
CREATE INDEX idx_expression_locale_links_locale ON expression_locale_links(locale_id, expression_id);

CREATE TABLE expression_readings (
  expression_id BIGINT NOT NULL,
  locale_id BIGINT NOT NULL,
  scheme TEXT NOT NULL,
  value TEXT NOT NULL,
  source_id BIGINT,
  PRIMARY KEY (expression_id, locale_id, scheme, value),
  FOREIGN KEY (expression_id) REFERENCES expressions(id) ON DELETE CASCADE,
  FOREIGN KEY (locale_id) REFERENCES language_locales(id) ON DELETE RESTRICT,
  FOREIGN KEY (source_id) REFERENCES sources(id) ON DELETE SET NULL
);

CREATE TABLE expression_edges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expression_a_id BIGINT NOT NULL,
  expression_b_id BIGINT NOT NULL,
  relation_mask BIGINT NOT NULL DEFAULT 1 CHECK (relation_mask BETWEEN 1 AND 7),
  score BIGINT NOT NULL DEFAULT 0,
  annotations_json TEXT NOT NULL DEFAULT '[]',
  created_by BIGINT,
  CHECK (expression_a_id < expression_b_id),
  UNIQUE (expression_a_id, expression_b_id),
  FOREIGN KEY (expression_a_id) REFERENCES expressions(id) ON DELETE CASCADE,
  FOREIGN KEY (expression_b_id) REFERENCES expressions(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_expression_edges_b_id ON expression_edges(expression_b_id);

CREATE TABLE expression_sources (
  expression_id BIGINT NOT NULL,
  source_id BIGINT NOT NULL,
  source_marker TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (expression_id, source_id, source_marker),
  FOREIGN KEY (expression_id) REFERENCES expressions(id) ON DELETE CASCADE,
  FOREIGN KEY (source_id) REFERENCES sources(id) ON DELETE SET NULL
);
CREATE INDEX idx_expression_sources_expression ON expression_sources(expression_id);

CREATE TABLE expression_edge_sources (
  edge_id BIGINT NOT NULL,
  source_id BIGINT NOT NULL,
  source_marker TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (edge_id, source_id, source_marker),
  FOREIGN KEY (edge_id) REFERENCES expression_edges(id) ON DELETE CASCADE,
  FOREIGN KEY (source_id) REFERENCES sources(id) ON DELETE SET NULL
);
CREATE INDEX idx_expression_edge_sources_edge ON expression_edge_sources(edge_id);

CREATE TABLE edge_votes (
  user_id BIGINT NOT NULL,
  edge_id BIGINT NOT NULL,
  vote BIGINT NOT NULL CHECK (vote IN (-1, 1)),
  PRIMARY KEY (user_id, edge_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (edge_id) REFERENCES expression_edges(id) ON DELETE CASCADE
);
CREATE INDEX idx_edge_votes_edge ON edge_votes(edge_id);

CREATE TABLE handbooks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  visibility TEXT NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'private')),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  managed_key TEXT,
  language_locale_id BIGINT,
  score BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (language_locale_id) REFERENCES language_locales(id) ON DELETE SET NULL
);
CREATE INDEX idx_handbooks_visibility_created ON handbooks(visibility, created_at DESC, id ASC);
CREATE INDEX idx_handbooks_visibility_score ON handbooks(visibility, score DESC, created_at DESC, id ASC);
CREATE UNIQUE INDEX idx_handbooks_managed_key ON handbooks(managed_key) WHERE managed_key IS NOT NULL;

CREATE TABLE handbook_votes (
  user_id BIGINT NOT NULL,
  handbook_id BIGINT NOT NULL,
  vote BIGINT NOT NULL CHECK (vote IN (-1, 1)),
  PRIMARY KEY (user_id, handbook_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (handbook_id) REFERENCES handbooks(id) ON DELETE CASCADE
);
CREATE INDEX idx_handbook_votes_handbook ON handbook_votes(handbook_id);

CREATE TABLE handbook_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  handbook_id BIGINT NOT NULL,
  title TEXT,
  position BIGINT NOT NULL,
  parent_section_id BIGINT,
  UNIQUE (handbook_id, position),
  FOREIGN KEY (handbook_id) REFERENCES handbooks(id) ON DELETE CASCADE,
  FOREIGN KEY (parent_section_id) REFERENCES handbook_sections(id) ON DELETE CASCADE
);
CREATE INDEX idx_handbook_sections_parent ON handbook_sections(handbook_id, parent_section_id, position, id);

CREATE TABLE handbook_section_items (
  section_id BIGINT NOT NULL,
  position BIGINT NOT NULL,
  expression_id BIGINT NOT NULL,
  PRIMARY KEY (section_id, position),
  UNIQUE (section_id, expression_id),
  FOREIGN KEY (section_id) REFERENCES handbook_sections(id) ON DELETE CASCADE,
  FOREIGN KEY (expression_id) REFERENCES expressions(id) ON DELETE RESTRICT
);

CREATE TABLE morphological_dimensions (
  code TEXT PRIMARY KEY,
  name_expression_id BIGINT NOT NULL,
  sort_order BIGINT NOT NULL UNIQUE,
  FOREIGN KEY (name_expression_id) REFERENCES expressions(id) ON DELETE RESTRICT
);
CREATE TABLE morphological_features (
  code TEXT PRIMARY KEY,
  dimension_code TEXT NOT NULL,
  name_expression_id BIGINT NOT NULL,
  sort_order BIGINT NOT NULL,
  UNIQUE (dimension_code, sort_order),
  FOREIGN KEY (dimension_code) REFERENCES morphological_dimensions(code) ON DELETE CASCADE,
  FOREIGN KEY (name_expression_id) REFERENCES expressions(id) ON DELETE RESTRICT
);

CREATE TABLE expression_form_edges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id BIGINT NOT NULL,
  lemma_id BIGINT NOT NULL,
  created_by BIGINT,
  CHECK (form_id <> lemma_id),
  UNIQUE (form_id, lemma_id),
  FOREIGN KEY (form_id) REFERENCES expressions(id) ON DELETE CASCADE,
  FOREIGN KEY (lemma_id) REFERENCES expressions(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_expression_form_edges_lemma_id ON expression_form_edges(lemma_id);
CREATE OR REPLACE FUNCTION prevent_reverse_expression_form_edge() RETURNS trigger AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM expression_form_edges WHERE form_id = NEW.lemma_id AND lemma_id = NEW.form_id) THEN
    RAISE EXCEPTION 'reverse expression form edge exists';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_expression_form_edges_no_reverse
BEFORE INSERT ON expression_form_edges
FOR EACH ROW EXECUTE FUNCTION prevent_reverse_expression_form_edge();

CREATE TABLE expression_form_edge_features (
  edge_id BIGINT NOT NULL,
  feature_code TEXT NOT NULL,
  PRIMARY KEY (edge_id, feature_code),
  FOREIGN KEY (edge_id) REFERENCES expression_form_edges(id) ON DELETE CASCADE,
  FOREIGN KEY (feature_code) REFERENCES morphological_features(code) ON DELETE RESTRICT
);

CREATE TABLE expression_splits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_expression_id BIGINT NOT NULL,
  target_expression_id BIGINT NOT NULL,
  created_by BIGINT,
  FOREIGN KEY (source_expression_id) REFERENCES expressions(id) ON DELETE RESTRICT,
  FOREIGN KEY (target_expression_id) REFERENCES expressions(id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE TABLE expression_split_moves (
  split_id BIGINT NOT NULL,
  edge_id BIGINT NOT NULL,
  PRIMARY KEY (split_id, edge_id),
  FOREIGN KEY (split_id) REFERENCES expression_splits(id) ON DELETE CASCADE,
  FOREIGN KEY (edge_id) REFERENCES expression_edges(id) ON DELETE RESTRICT
);

CREATE TABLE ui_locales (
  project_id TEXT NOT NULL,
  locale_id BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'archived')),
  mapping_revision BIGINT NOT NULL DEFAULT 0,
  activation_source TEXT CHECK (activation_source IN ('system', 'auto', 'manual')),
  activated_at TEXT,
  activated_by BIGINT,
  created_by BIGINT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  PRIMARY KEY (project_id, locale_id),
  FOREIGN KEY (locale_id) REFERENCES language_locales(id) ON DELETE RESTRICT,
  FOREIGN KEY (activated_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE ui_messages (
  project_id TEXT NOT NULL,
  message_key TEXT NOT NULL,
  source_expression_id BIGINT NOT NULL,
  source_text TEXT NOT NULL,
  placeholders_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('draft', 'active', 'archived')),
  PRIMARY KEY (project_id, message_key),
  FOREIGN KEY (source_expression_id) REFERENCES expressions(id) ON DELETE RESTRICT
);
CREATE INDEX idx_ui_messages_source_expression ON ui_messages(project_id, status, source_expression_id);

CREATE TABLE user_preferences (
  user_id BIGINT NOT NULL,
  preference_key TEXT NOT NULL,
  value_json TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
  PRIMARY KEY (user_id, preference_key),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);


ALTER TABLE languages
  ADD CONSTRAINT languages_name_expression_fk FOREIGN KEY (name_expression_id) REFERENCES expressions(id);
ALTER TABLE scripts
  ADD CONSTRAINT scripts_name_expression_fk FOREIGN KEY (name_expression_id) REFERENCES expressions(id);
ALTER TABLE regions
  ADD CONSTRAINT regions_name_expression_fk FOREIGN KEY (name_expression_id) REFERENCES expressions(id);
ALTER TABLE language_locales
  ADD CONSTRAINT language_locales_name_expression_fk FOREIGN KEY (name_expression_id) REFERENCES expressions(id);
